### DISCUSSION TITLE
In the Kubernetes cluster environment built using kubeadm, following the QuickStart does not deploy the InterStepBufferService.

### DISCUSSION THREAD

**Discussion by sesame0224** [numaproj/numaflow#2187] [Q&A] [answered]
Following the [QuickStart](https://numaflow.numaproj.io/quick-start/#installing-numaflow), applying a manifest file like the one below to deploy the InterStepBuffer does not complete the deployment.

```
apiVersion: numaflow.numaproj.io/v1alpha1
kind: InterStepBufferService
metadata:
  name: default
spec:
  jetstream:
    version: 2.10.17 
    persistence:
      volumeSize: 3Gi
```

```
k get -n default pod -o wide
NAME                  READY   STATUS    RESTARTS   AGE     IP       NODE     NOMINATED NODE   READINESS GATES
isbsvc-default-js-0   0/3     Pending   0          6h47m   <none>   <none>   <none>           <none>
isbsvc-default-js-1   0/3     Pending   0          6h47m   <none>   <none>   <none>           <none>
isbsvc-default-js-2   0/3     Pending   0          6h47m   <none>   <none>   <none>           <none>
```

Upon checking the pod details, it was found to be pending because the PVC is not bound.

```
kubectl describe pod isbsvc-default-js-0 -n default
Name:             isbsvc-default-js-0
...
Events:
  Type     Reason            Age                     From               Message
  ----     ------            ----                    ----               -------
  Warning  FailedScheduling  2m43s (x83 over 6h48m)  default-scheduler  0/3 nodes are available: pod has unbound immediate PersistentVolumeClaims. not found
```

I believe it is necessary to either manually create a PersistentVolume (PV) or deploy an appropriate StorageClass to address this issue. I would greatly appreciate your guidance on the appropriate way to handle this.
