### DISCUSSION TITLE
Rate Limiting Message Processing from Kafka Source: Best Practices for Consistent Processing

### DISCUSSION THREAD

**Discussion by 4rpit** [numaproj/numaflow#2216] [Q&A] [answered]
I'm working with a processing pipeline where Kafka is the source of messages. Currently, the processing rate is unbounded, leading to inconsistent processing rates and potential downstream bottlenecks. what configuration I can add to the source for a better and bounded processing rate

**Comment by vigith** [comment]
To do throttling on a particular vertex you can do the following:

* reduce the [readBatchSize](https://numaflow.numaproj.io/user-guide/reference/pipeline-tuning/) of the vertex, set it to a number such that your downstream can handle concurrently (batchSize * number of pods will be the approximate concurrent requests on your downstream)
* reduce the number of max pods (`scale.max`) of the vertex so it won't autoscale to something your downstream cannot handle. this can be achieved via [autoscaling](https://numaflow.numaproj.io/user-guide/reference/autoscaling/)

**Reply by vigith** [reply]
You can do the same trick for the Kafka Source too.

**Reply by 4rpit** [reply]
Thanks Vigith, I see the `spec. limit `is part of the Pipeline definition, while I tried to `limit` under the source Vertex for the Kafka it is a validation error - do you mean that the `spec.limit` also works for type Vertex

**Reply by whynowy** [reply]
There is an example in https://numaflow.numaproj.io/user-guide/reference/pipeline-tuning/ for configuration in vertex level.

```yaml
  vertices:
    - name: cat
      udf:
        builtin:
          name: cat
      limits:
        readBatchSize: 200 # It overrides the default limit "100"
```

**Reply by 4rpit** [reply]
hey folks back again, I did some experiments with this number and was not able to do throttling on the source vertex - even if I keep the `readBatchSize`  either 1 or 100 it produces the same load downstream could the value for [DefaultKafkaHandlerChannelSize](https://github.com/numaproj/numaflow/blob/main/pkg/sources/source.go#L352C16-L352C30) of 100 is the reason it is keeping 100 messages from Kafka and not following the limits in the Vertex

**Reply by vigith** [reply]
could you please share your pipeline config?

**Reply by 4rpit** [reply]
```
kind: Pipeline
apiVersion: numaflow.numaproj.io/v1alpha1
metadata:
  name: pipeline-name
  namespace: default
  labels:
  annotations:
  finalizers:
    - pipeline-controller
spec:
  vertices:
    - name: kafka-source
      source:
        kafka:
          brokers:
            - kafka-headless.kafka.svc.cluster.local:9092
          topic: CDC
          consumerGroup: ng-cg-1
      limits:
        readBatchSize: 1
      scale:
        min: 1
        max: 2
    - name: processor
      udf:
        container:
          image: image-id
    - name: post-processor
      udf:
        container:
          image: image-id
    - name: sink
      sink:
        log: {}
  edges:
    - from: kafka-source
      to: processor
      conditions: null
    - from: processor
      to: post-processor
      conditions: null
    - from: post-processor
      to: sink
      conditions: null
```
this is the pipeline (omit few details)

**Reply by vigith** [reply, marked as answer]
add limits to the UDF

```
    - name: processor
      udf:
        container:
          image: image-id
      limits:
        readBatchSize: 1
```
