### DISCUSSION TITLE
Best practices for Inter Step Buffer (Nats JetStream)?

### DISCUSSION THREAD

**Discussion by qianbeibuzui** [numaproj/numaflow#2239] [Q&A]
My Inter Step Buffer (Nats JetStream) and vertices settings are shown in the figure:
<img width="543" alt="企业微信截图_17326400083818" src="https://github.com/user-attachments/assets/6311b05f-c199-4fb7-bdd2-7542e731b143">

I have three doubts here:
What is the relationship between JetStream.maxMss: 50000 and verticals.limits.bufferMaxLength: 30000? If I set two vertices in the Pipeline with a buffer MaxLength of 30000, will there be a bug? What is the best practice plan?
﻿
2. JetStream.max_cemory_store: 1073741824, I set 1Gi of memory here, but the actual pod is occupying 4GB of memory. What is the reason for this? And when preparing to break through 4G memory, it seems to automatically release memory? As shown in the picture:
<img width="722" alt="企业微信截图_17326319263902" src="https://github.com/user-attachments/assets/fe45b8b1-97a7-49cb-9dd8-12e44713b0dc">

3.What is the best practice for memory and maxDLLs for Inter Step Buffer (Nats JetStream)?

**Comment by kohlisid** [comment]
Hey @qianbeibuzui 
I will try to cover your queries here!

1. _**JetStream.maxMss: 50000 and verticals.limits.bufferMaxLength: 30000? If I set two vertices in the Pipeline with a buffer MaxLength of 30000**_

Jetstream maxMsgs are the limit on the number of messages that can be stored in a stream, this will apply as an upper bound. Beyond these limits the discard policy kicks in and the messages are deleted/discarded accordingly.

`bufferMaxLength` is a soft limit getting enforced at the Numaflow level, where as a platform we try to not write more than this number to the buffer. And if the availability crosses the threshold, the user can specifify what action they want to take. Default is Numaflow retrying until success. 

So there is no bug, Numaflow will try to honor the bufferMaxLength first. JetStream.maxMss is honored at a stream level by Jetstream.

2. max_memory_store
`max_memory_store | Maximum size of the 'memory' storage | Default is 75% of available memory`

This is the Jetstream server resource limit that is used, if you are using memory mode they streams will be stored in memory.


Also for your `automatically release memory`
This could partly be a behavior from the golang GC. Could you let us know whats the GOMEMLIMIT getting used in your server. 



3. What is the best practice for memory and maxDLLs for Inter Step Buffer (Nats JetStream)?
To answer this I would need to understand a bit more of your use case, TPS and you data/msg size


I see that you are using stream replication as **1 with in memory mode.** This makes it highly temporal
Any reason for this specifically? 

For resiliency we should be using a File mode, along with a higher replication factor. 
Typical usage to operate in typical outages and balance performance would be a file-based stream with R=3.

**Reply by qianbeibuzui** [reply]
1.JetStream.maxMss: 50000 and verticals.limits.bufferMaxLength: 30000 * 2.  60000>50000.If Numaflow's cache reaches 30000 * 2, will messages be lost due to JetStream. maxMax: 50000?

![image](https://github.com/user-attachments/assets/7209d152-4f9a-471b-9dab-9ba47297d952)

2.you are using stream replication as 1 with in memory mode. This makes it highly temporal
Any reason for this specifically?
It's because I want to pursue higher TPS.

**Comment by vigith** [comment]
> It's because I want to pursue higher TPS.

What is the TPS you are trying to hit? Also, are you doing [reduce](https://numaflow.numaproj.io/user-guide/user-defined-functions/reduce/reduce/) operations also in the pipeline?

**Reply by qianbeibuzui** [reply]
> > 因为我想追求更高的TPS。
> 
> 您要达到的 TPS 是多少？此外，您是否也在管道中执行[减​​少操作？](https://numaflow.numaproj.io/user-guide/user-defined-functions/reduce/reduce/)

1W qps。But I have noticed that the official update for MonoVertex has been released, but my attempt to use MonoVertex.source.kafka has failed. It seems that MonoVertex does not have a source. kafka. This requires either official implementation or my own implementation of udsource.kafka.
Also, can you answer the first question I described?
![image](https://github.com/user-attachments/assets/6fc0596b-b739-427c-92ac-cf576b57cb21)

Also, can you answer the first question I described?

JetStream.maxMss: 50000 且verticals.limits.bufferMaxLength: 30000 * 2. 60000>50000.如果Numaflow的缓存达到了30000 * 2，会不会因为JetStream.maxMax: 50000而丢失消息？

**Reply by qianbeibuzui** [reply]
> > It's because I want to pursue higher TPS.
> 
> What is the TPS you are trying to hit? Also, are you doing [reduce](https://numaflow.numaproj.io/user-guide/user-defined-functions/reduce/reduce/) operations also in the pipeline?

Also, are you doing [reduce](https://numaflow.numaproj.io/user-guide/user-defined-functions/reduce/reduce/) operations also in the pipeline?

It's not working yet. But I have a premonition: it is highly likely to be used in the future.

**Comment by vigith** [comment]
> But I have noticed that the official update for MonoVertex has been released, but my attempt to use MonoVertex.source.kafka has failed. It seems that MonoVertex does not have a source. kafka. This requires either official implementation or my own implementation of udsource.kafka.

That is right. MonoVertex does not support builtin Kafka yet due to some breaking changes. We will support it in 1.5 release (approx ETA Feb/01/2025).

**Comment by vigith** [comment]
> What is the relationship between JetStream.maxMss: 50000 and verticals.limits.bufferMaxLength: 30000? If I set two vertices in the Pipeline with a buffer MaxLength of 30000, will there be a bug? What is the best practice plan?

Each vertex has its own buffer, so each vertex will get independent buffers with independent limits. You can have 2 vertices without any problems.

**Reply by qianbeibuzui** [reply]
I'm very sorry to bother you again. I seem to have encountered a memory leak situation.
I continue to conduct stress tests on numaflow using TPS: 7000. Based on my continuous observation of the "isbsvc default js-x)" pod, the memory keeps rising until an Error (OOMKilled) occurs.
As shown in the figure:
![image](https://github.com/user-attachments/assets/1e4ce638-ba50-4511-894f-43a12f2bbbfa)
![image](https://github.com/user-attachments/assets/36895b0c-5a7d-4370-9bb9-93f67356b12e)


This is my InterStepBufferService setting:

```
kind: InterStepBufferService
apiVersion: numaflow.numaproj.io/v1alpha1
metadata:
  name: default
  namespace: default
spec:
  jetstream:
    version: latest
    replicas: 3
    containerTemplate:
      resources:
        limits:
          cpu: "4"
          memory: 8Gi
    persistence:
      storageClassName: cbs
      volumeSize: 100Gi
    bufferConfig: |
      stream:
        # 0: Limits, 1: Interest, 2: WorkQueue
        retention: 0
        maxMsgs: 50000
        maxAge: 24h
        maxBytes: -1
        # 0: File, 1: Memory
        storage: 0         ### <- this switch to RAM only mode
        replicas: 3        ### <- this does not replicate data in the streams
        duplicates: 15m
  config:
    jetstream:
      streamConfig: |
        stream:
          duplicates: 15m
          maxage: 24h
          maxbytes: -1
          maxmsgs: 50000
          replicas: 3
          retention: 0
          storage: 0
  type: jetstream
```

This is my Pipeline setting:

```
kind: Pipeline
apiVersion: numaflow.numaproj.io/v1alpha1
metadata:
  name: bi-device-pipeline
  namespace: default
spec:
  vertices:
    - name: in
      source:
        kafka:
          brokers:
            - 10.0.2.224:9092
          topic: ad_pool_shiyuegame_com.device
          consumerGroup: huijuan-consumer-group-device
          tls: null
          config: >
            consumer:
              offsets:
                initial: -2 # -2 for sarama.OffsetOldest, -1 for sarama.OffsetNewest. Default to sarama.OffsetNewest.
          sasl: null
          kafkaVersion: 2.8.1
      containerTemplate:
        resources:
          limits:
            cpu: 300m
            memory: 322122547200m
          requests:
            cpu: 300m
            memory: 322122547200m
      imagePullSecrets:
        - name: fxzc-image
      scale:
        min: 1
        max: 1
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
    - name: device
      udf:
        container:
          image: xx/device_mapper:latest
          resources: {}
        builtin: null
        groupBy: null
      containerTemplate:
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
      imagePullSecrets:
        - name: fxzc-image
      limits:
        readBatchSize: 5000
        readTimeout: 30s
        bufferMaxLength: 20000
        bufferUsageLimit: 85
      scale:
        min: 1
        max: 1
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
    - name: starrocks
      sink:
        udsink:
          container:
            image: xx/starrocks_sink:latest
            resources: {}
        retryStrategy: {}
      containerTemplate:
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
      imagePullSecrets:
        - name: fxzc-image
      limits:
        readBatchSize: 5000
        readTimeout: 30s
        bufferMaxLength: 20000
        bufferUsageLimit: 85
      scale:
        min: 1
        max: 1
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
  edges:
    - from: in
      to: device
      conditions: null
      onFull: retryUntilSuccess
    - from: device
      to: starrocks
      conditions: null
      onFull: retryUntilSuccess
  lifecycle:
    deleteGracePeriodSeconds: 30
    desiredPhase: Running
    pauseGracePeriodSeconds: 30
  limits:
    readBatchSize: 1000
    bufferMaxLength: 20000
    bufferUsageLimit: 85
    readTimeout: 30s
  watermark:
    maxDelay: 0s
  templates:
    daemon:
      imagePullSecrets:
        - name: fxzc-image
    job:
      imagePullSecrets:
        - name: fxzc-image
    sideInputsManager:
      imagePullSecrets:
        - name: fxzc-image
status:
  conditions:
    - type: Configured
      status: "True"
      lastTransitionTime: 2024-11-27T10:48:02Z
      reason: Successful
      message: Successful
    - type: DaemonServiceHealthy
      status: "True"
      lastTransitionTime: 2024-11-27T10:48:02Z
      reason: Successful
      message: Successful
    - type: Deployed
      status: "True"
      lastTransitionTime: 2024-11-27T10:48:02Z
      reason: Successful
      message: Successful
    - type: SideInputsManagersHealthy
      status: "True"
      lastTransitionTime: 2024-11-27T10:48:02Z
      reason: NoSideInputs
      message: No Side Inputs attached to the pipeline
    - type: VerticesHealthy
      status: "True"
      lastTransitionTime: 2024-11-27T10:48:02Z
      reason: Successful
      message: All vertices are healthy
  phase: Running
  lastUpdated: 2024-11-27T10:48:02Z
  vertexCount: 3
  sourceCount: 1
  sinkCount: 1
  udfCount: 1
  mapUDFCount: 1
  reduceUDFCount: 0
  observedGeneration: 4
```

numaflow:v1.4.0
k8s:v1.24.4
nats:2.10.17

**Comment by kohlisid** [comment]
Hello @qianbeibuzui 
What is the msg size of the payloads that you are using?

**Reply by qianbeibuzui** [reply]
> Hello @qianbeibuzui What is the msg size of the payloads that you are using?

Is it the 'max_mayload' setting item? No settings, using default values.

![image](https://github.com/user-attachments/assets/4905fcfc-7c44-44ed-a64e-c870548559c2)

**Comment by kohlisid** [comment]
@qianbeibuzui I'm referring the to data that is getting stored in the stream. What is the average size of the messages flowing in the pipeline?

**Reply by qianbeibuzui** [reply]
> @qianbeibuzui我指的是存储在流中的数据。管道中流动的消息的平均大小是多少？

7000/sec

**Reply by kohlisid** [reply]
Sorry that would be throughput. 
Payload size in Kb maybe?

**Reply by qianbeibuzui** [reply]
> 抱歉，那应该是吞吐量。 也许有效负载大小（单位为 KB）？

Single item:1.13 KB

**Reply by kohlisid** [reply]
And you are using a limits queue, with file storage mode with Replication 3 correct?

**Reply by qianbeibuzui** [reply]
When concurrency is low, it is relatively stable, and it seems that the problem only occurs when concurrency is high.
![image](https://github.com/user-attachments/assets/edcc0e6a-dfab-473e-9ef5-aa6c1509cdef)
![image](https://github.com/user-attachments/assets/c2496340-a219-4775-b64e-1097aa74ffeb)

**Reply by kohlisid** [reply]
Which concurrency are you referring to here specifically? Messages/sec?

**Reply by qianbeibuzui** [reply]
> And you are using a limits queue, with file storage mode with Replication 3 correct?

Based on your previous advice, I have already used file storage and Replication=3

![image](https://github.com/user-attachments/assets/a3a5d1c9-f066-4aac-bbe9-1775f99a44c0)

**Reply by qianbeibuzui** [reply]
> Messages/sec

Messages/sec=7000/sec will reproduce

**Comment by qianbeibuzui** [comment]
@kohlisid Do you need me to provide any additional information to assist you in troubleshooting?

**Reply by kohlisid** [reply]
In my experiments with a single stream, I have seen the Jetstream server use higher memory than the stream size per se. 

Would you like to try with a higher memory request and limit to see how much memory is getting consumed at a stable state for 7k?
Additionally, we can set a lower GOMEMLIMIT value to try and invoke the GC earlier 

Would you like to try that out?
```
spec:
  jetstream:
    replicas: 3
    metricsContainerTemplate:
      env:
        - name: GOMEMLIMIT
          value: "19327352832"  
    reloaderContainerTemplate:
      env:
        - name: GOMEMLIMIT
          value: "19327352832"
    containerTemplate:
      env:
        - name: GOMEMLIMIT
          value: "19327352832"
      resources:
        limits:
          cpu: 6
          memory: 24Gi
        requests:
          cpu: 6
          memory: 24Gi

```
We have been tracking this with Jetstream as well
Ref:
https://github.com/nats-io/nats-server/issues/5739
https://github.com/nats-io/nats-server/issues/6163
https://github.com/nats-io/nats-server/issues/6010
