### DISCUSSION TITLE
Channel and window close issue with Reduce Vertex/UDF

### DISCUSSION THREAD

**Discussion by PRATHAM2002-DS** [numaproj/numaflow#2363] [Q&A]
## My usecase Description:

I am using Reduce with fixed window and keyed set to false with source and sink as Kafka. The vertex needs to accumulate data in given time window which is set to 60s and send it to another external service for performing operations on those events. (All config values mentioned are used for testing/poc). i will add both UDF and Pipeline code below.

## Issue Description:  

When the first event hits Reduce function the event stays in for loop that works on datum data stream, and the for loop does not terminate and process data even after 60 s are over. The frequency of events coming in my usecase is not fixed and continuous i.e 2 events may come in first second and Third can come after 2 minutes for example. The event stay in loop or channel until the event comes just before window closes. I Also tried same UDF with keyed set to True but getting similar behaviour.

## Expected Behaviour:

I expected that Reduce UDF will accumulate what ever events come in 60 s and after window length is completed it will close channel and terminate loop to process these accumulated events, even if there is no continuous event hitting Reduce. So event after first few seconds if no event came I expected it to terminate loop/ close channel and process event accumulated in first few seconds.

## Actual Behaviour:

The events coming in first few seconds stay in loop and loop does not get terminated/channel does not close even after 60s is completed. Suddenly if some another event comes just before this window length is completed the channel closes and process all previous windows accumulated messages.

## Pipeline Code:

```kind: Pipeline
apiVersion: numaflow.numaproj.io/v1alpha1
metadata:
  name: nf-business-pipeline
  labels:
    numaflow.numaproj.io/component: pipeline
    numaflow.numaproj.io/name: nf-business-pipeline
    numaflow.numaproj.io/part-of: numaflow
    numaflow.numaproj.io/created-by: controller-manager
  annotations:
    numaflow.numaproj.io/description: A numaflow meta pipeline which will handle for business execution
    numaflow.numaproj.io/owner: #owner
    numaflow.numaproj.io/pipeline-name: nf-business-pipeline
    numaflow.numaproj.io/test: "true"
spec:
  templates:
    daemon:
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      imagePullSecrets:
        - name: github-docker-registry
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: eks.amazonaws.com/capacityType   #AWS
                operator: In
                values:
                - SPOT
          - weight: 1
            preference:
              matchExpressions:
              - key: lifecycle     #Azure
                operator: In
                values:
                - spot
          - weight: 1
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-provisioning  #GCP
                operator: In
                values:
                - spot          
    job:
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      imagePullSecrets:
        - name: github-docker-registry
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: eks.amazonaws.com/capacityType   #AWS
                operator: In
                values:
                - SPOT
          - weight: 1
            preference:
              matchExpressions:
              - key: lifecycle     #Azure
                operator: In
                values:
                - spot
          - weight: 1
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-provisioning  #GCP
                operator: In
                values:
                - spot
    # If using custom service accounts, set vertex to null
    vertex: null
    sideInputsManager:
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      imagePullSecrets:
        - name: github-docker-registry
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: eks.amazonaws.com/capacityType   #AWS
                operator: In
                values:
                - SPOT
          - weight: 1
            preference:
              matchExpressions:
              - key: lifecycle     #Azure
                operator: In
                values:
                - spot
          - weight: 1
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-provisioning  #GCP
                operator: In
                values:
                - spot     
  vertices:
    - name: bl-cdc-source
      source:
        kafka:
          brokers:
            - # kafka broker
          topic: BUSINESS
          consumerGroup: nf-pipeline-bl-execution
          tls: null
          sasl: null
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      tolerations:
        - key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot
          effect: NoSchedule
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: eks.amazonaws.com/capacityType   #AWS
                operator: In
                values:
                - SPOT
          - weight: 1
            preference:
              matchExpressions:
              - key: lifecycle     #Azure
                operator: In
                values:
                - spot
          - weight: 1
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-provisioning  #GCP
                operator: In
                values:
                - spot            
      imagePullSecrets:
        - name: github-docker-registry
      scale:
        min: 1
        max: 1
    - name: bl-cdc-processor
      udf:
        container:
          image: # image of my go script UDF
          command:
            - ./main
            - execute
            - business-runner
          resources: {}
        groupBy: 
          window:
            fixed:
              length: 60s
          keyed: true
          storage:
            emptyDir: {}
        builtin: null
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      tolerations:
        - key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot
          effect: NoSchedule
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: eks.amazonaws.com/capacityType   #AWS
                operator: In
                values:
                - SPOT
          - weight: 1
            preference:
              matchExpressions:
              - key: lifecycle     #Azure
                operator: In
                values:
                - spot
          - weight: 1
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-provisioning  #GCP
                operator: In
                values:
                - spot            
      imagePullSecrets:
        - name: github-docker-registry
      serviceAccountName: numaflow-sa-default-ns
      scale:
        min: 1
        max: 1
    - name: bl-dlq-sink
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      imagePullSecrets:
        - name: github-docker-registry
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: eks.amazonaws.com/capacityType   #AWS
                operator: In
                values:
                - SPOT
          - weight: 1
            preference:
              matchExpressions:
              - key: lifecycle     #Azure
                operator: In
                values:
                - spot
          - weight: 1
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-provisioning  #GCP
                operator: In
                values:
                - spot
      sink:
        kafka:
          brokers:
            -  # kafka broker
          topic: "BUSINESS_DLQ"
      scale:
        disabled: false
        min: 1
        max: 1

        
  edges:
    - from: bl-cdc-source
      to: bl-cdc-processor
      conditions: null
    - from: bl-cdc-processor
      to: bl-dlq-sink
      conditions:
        tags:
          values:
            - dlq   
   ```

## Script Code:

```package businesslineage

import (
	"context"
	"fmt"
	"os"
	"time"

	"github.com/marketplace-go/common/atlas"
	"github.com/marketplace-go/common/cache/redis"
	es "github.com/marketplace-go/common/elasticsearch"
	"github.com/marketplace-go/common/heracles"
	gatekeeper "github.com/marketplace-go/common/locks"
	"github.com/marketplace-go/constant"
	"github.com/marketplace-go/scripts"
	"github.com/numaproj/numaflow-go/pkg/reducer"
	"github.com/rs/zerolog/log"
)


func (f *SumReducerCreator) Execute(args []string) {
	if err := reducer.NewServer(f).Start(context.Background()); err != nil {
		log.Err(err).Msg("Failed to start the reducer server")
		os.Exit(1)
	}
}

// SumReducerCreator implements the reducer.ReducerCreator interface which creates a reducer
type SumReducerCreator struct {
}

func (s *SumReducerCreator) Create() reducer.Reducer {
	return &Sum{sum: []string{}}
}

// Sum is a reducer that sum up the values for the given keys
type Sum struct {
	sum []string
}

// Reduce function processes multiple events within a time window
func (f *Sum) Reduce(ctx context.Context, keys []string, datums <-chan reducer.Datum, md reducer.Metadata) reducer.Messages {
	fmt.Println("BL: Reduce called")

	for datum := range datums { // Process each datum until the channel is closed
		// Retrieve the value from the current datum
		rawData := datum.Value()
		eventKey := string(rawData)

		// Append the data to the accumulated result
		f.sum = append(f.sum, eventKey)

		fmt.Println("BL: Event Key: " + eventKey)
	}

	// Print all accumulated data once the channel is fully consumed
	fmt.Println("BL: Final accumulated data: " + fmt.Sprintf("%v", f.sum))

	return nil // Exit the function after all datums are processed
}

func init() {
	scripts.Register(constant.BusinessLineageRunner, &SumReducerCreator{})
}
```

## LOGS:
Logs showing inconsistency when keyed set to false:

```
BL: Reduce called
BL: Event Key: {"assetGuid":"cc878da0-e9af-48f6-a52e-6d2f2d2b0a22","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"}
BL: Event Key: {"assetGuid":"a9df1b19-0e0c-4ed6-8d94-6c258f265333","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"}
BL: Event Key: {"assetGuid":"a9df1b19-0e0c-4ed6-8d94-6c258f265333","edgeLabel":"","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"}
BL: Event Key: {"assetGuid":"e3afa960-1b2b-4cdb-8fd7-84a3ef620189","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"}
BL: Event Key: {"assetGuid":"e3afa960-1b2b-4cdb-8fd7-84a3ef620189","edgeLabel":"","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"}
BL: Reduce called
BL: Event Key: {"assetGuid":"cc878da0-e9af-48f6-a52e-6d2f2d2b0a22","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"}
BL: Reduce called
BL: Event Key: {"assetGuid":"a9df1b19-0e0c-4ed6-8d94-6c258f265333","edgeLabel":"","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"}
BL: Event Key: {"assetGuid":"a9df1b19-0e0c-4ed6-8d94-6c258f265333","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"}
BL: Reduce called
BL: Event Key: {"assetGuid":"e3afa960-1b2b-4cdb-8fd7-84a3ef620189","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"}
BL: Event Key: {"assetGuid":"e3afa960-1b2b-4cdb-8fd7-84a3ef620189","edgeLabel":"","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"}
BL: Final accumulated data: [{"assetGuid":"cc878da0-e9af-48f6-a52e-6d2f2d2b0a22","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"}]
BL: Final accumulated data: [{"assetGuid":"cc878da0-e9af-48f6-a52e-6d2f2d2b0a22","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"} {"assetGuid":"a9df1b19-0e0c-4ed6-8d94-6c258f265333","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"} {"assetGuid":"a9df1b19-0e0c-4ed6-8d94-6c258f265333","edgeLabel":"","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"} {"assetGuid":"e3afa960-1b2b-4cdb-8fd7-84a3ef620189","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"} {"assetGuid":"e3afa960-1b2b-4cdb-8fd7-84a3ef620189","edgeLabel":"","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"}]

```

Log showing inconsistency when keyed set to true:

```
BL: Reduce called
BL: Event Key: {"assetGuid":"asset1","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"}
BL: Reduce called
BL: Event Key: {"assetGuid":"a9df1b19-0e0c-4ed6-8d94-6c258f265333","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"}
BL: Event Key: {"assetGuid":"a9df1b19-0e0c-4ed6-8d94-6c258f265333","edgeLabel":"edgeLabel1","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"}
BL: Reduce called
BL: Event Key: {"assetGuid":"e3afa960-1b2b-4cdb-8fd7-84a3ef620189","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"}
BL: Event Key: {"assetGuid":"e3afa960-1b2b-4cdb-8fd7-84a3ef620189","edgeLabel":"edgeLabel2","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"}
BL: Reduce called
BL: Event Key: {"assetGuid":"a9df1b19-0e0c-4ed6-8d94-6c258f265333","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"}
BL: Event Key: {"assetGuid":"a9df1b19-0e0c-4ed6-8d94-6c258f265333","edgeLabel":"edgeLabel3","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"}
BL: Event Key: {"assetGuid":"cc878da0-e9af-48f6-a52e-6d2f2d2b0a22","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"}
BL: Event Key: {"assetGuid":"cc878da0-e9af-48f6-a52e-6d2f2d2b0a22","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"}
BL: Final accumulated data: [{"assetGuid":"e3afa960-1b2b-4cdb-8fd7-84a3ef620189","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"} {"assetGuid":"e3afa960-1b2b-4cdb-8fd7-84a3ef620189","edgeLabel":"","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"} {"assetGuid":"a9df1b19-0e0c-4ed6-8d94-6c258f265333","edgeLabel":"","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"} {"assetGuid":"a9df1b19-0e0c-4ed6-8d94-6c258f265333","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"} {"assetGuid":"e3afa960-1b2b-4cdb-8fd7-84a3ef620189","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"} {"assetGuid":"e3afa960-1b2b-4cdb-8fd7-84a3ef620189","edgeLabel":"","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"} {"assetGuid":"a9df1b19-0e0c-4ed6-8d94-6c258f265333","edgeLabel":"","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"} {"assetGuid":"a9df1b19-0e0c-4ed6-8d94-6c258f265333","operation":"ADD","productGuid":"b72034c4-be31-44cd-9fca-2ade5d5295fb"}]

```

Note All logs after "Reduce called" indicate different window and finally due to some event coming at Reduce UDF just before some window length completes, all grouped messages from different windows got processed.

## Question:

-> Is Reduce correct for my usecase ?
-> When I used storage config it stored and retried the unprocessed event but never removed those event even after successful retry, do we need to handle this explicitly? Config shown below:

```
storage:
            persistentVolumeClaim:
              volumeSize: 2Gi
              accessMode: ReadWriteOnce
```

**Comment by vigith** [comment]
are you incrementing the event-time in the events at the source? the 60s is based on the how the time progresses at source.

**Reply by PRATHAM2002-DS** [reply]
So my source is an in-built kafka and there are multiple producers which will emmit events to this kafka topic immediately when an event is created. Kafka will store event-time for each event when it writes to topic, so latest event will have event-time greater than previous one. Here I wanted to write a pipeline which consumes these events and chunk events coming based on time and send the grouped messages to external service to process.

**Reply by PRATHAM2002-DS** [reply]
Another way I tried to do chunking was using Map and in-memory batching but on pod restart I was losing data. Hence I was trying a poc with reduce.

**Reply by PRATHAM2002-DS** [reply]
The behaviour I have mentioned above (in original question) with reduce, is it an expected behaviour?

**Reply by vigith** [reply]
`return nil // Exit the function after all datums are processed` .. you should return the output of Reduce function so it can be forwarded to the next vertex.

**Reply by PRATHAM2002-DS** [reply]
I will surely try this, but if you see logs the evnts coming in first few seconds stay in the for-loop as channel does not get closed and do not come to this return statement even after window length is completed. These events only exit this loop when another event hits this function just before some other windows length is completed.

**Reply by vigith** [reply]
> These events only exit this loop when another event hits this function just before some other windows length is completed. 
> 

That is due to idling, I have pasted the link in the discussion

**Comment by vigith** [comment]
https://numaflow.numaproj.io/user-guide/user-defined-functions/reduce/windowing/windowing/

**Comment by vigith** [comment]
if you set key to true, you will have to set the keys in the pervious map vertex.

**Comment by vigith** [comment]
> So event after first few seconds if no event came I expected it to terminate loop/ close channel and process event accumulated in first few seconds.

you will have to turn on [idle detection](https://numaflow.numaproj.io/core-concepts/watermarks/#idle-detection) if your source is not emitting data.

**Comment by PRATHAM2002-DS** [comment]
Can you help me with following question @vigith 

> When I used storage config it stored and retried the unprocessed event but never removed those event even after successful retry, do we need to handle this explicitly? Config shown below:

```
storage:
            persistentVolumeClaim:
              volumeSize: 2Gi
              accessMode: ReadWriteOnce
  
 ```

**Reply by PRATHAM2002-DS** [reply]
After every new event or restart the store put some stored previous events in channel to process again.

**Reply by yhl25** [reply]
After the window is successfully closed and  the responses are forwarded to the next vertex, the events of that window will be cleared from the storage. Incase of restarts we replay the events that are persisted in the storage before reading the new set of events to make sure there is no data loss, after the window is closed those events will be cleared from the store.

**Comment by PRATHAM2002-DS** [comment]
@yhl25 @vigith if I use keyed events , set keyed: true for this reduce vertex and partitions:2 value to 2. Does this guarantee ordering? Will all events with same key be consumed by one partition?

**Reply by vigith** [reply]
> Does this guarantee ordering? 

There will be temporal ordering, the key for same window will be send to the same reduce function.

> Will all events with same key be consumed by one partition?

Yes, same key will end up in the same reduce function for that window.

**Comment by PRATHAM2002-DS** [comment]
@yhl25 @vigith suppose I set window length as 60s and the processing for events in first window has not yet completed and events from second window (say 60-120s) hit reduce function, does this affect events from first window? Will I loose the unprocessed events from first window or any other side effect that I should take care of?

**Reply by yhl25** [reply]
It should not affect, windows are unique per reducer. Messages of one window will always be forwarded to one instance of the reducer. They never overlap, and one window should not affect another.

**Reply by PRATHAM2002-DS** [reply]
@yhl25 in this case where the second window will not affect and not wait till all events from first window are processed completely, the order of executing events wont be maintained right?

**Reply by vigith** [reply]
second window is completely independent of the first window. since there is a temporal causality within the windows, second cannot close before first, so ordering is not lost.

**Comment by PRATHAM2002-DS** [comment]
@yhl25 @vigith I had implemented Reduce UDF with idle detection using numaflow v1.1.6 and it was working fine on this version, but idle detection feature stopped working when I updated numaflow version to v1.4.4 . Is there any behavioural change with idle detection ?

**Reply by vigith** [reply]
that should not happen. let us test and confirm it for you.

**Reply by PRATHAM2002-DS** [reply]
@vigith did the team get time to test this?

**Reply by vigith** [reply]
we tested and we couldn't see any problem /cc @adarsh0728 
could you please share the pipeline spec you are using?

**Reply by PRATHAM2002-DS** [reply]
@vigith this is the spec for pipeline.

```
kind: Pipeline
apiVersion: numaflow.numaproj.io/v1alpha1
metadata:
  name: nf-business-lineage-pipeline
  labels:
    numaflow.numaproj.io/component: pipeline
    numaflow.numaproj.io/name: nf-business-lineage-pipeline
    numaflow.numaproj.io/part-of: numaflow
    numaflow.numaproj.io/created-by: controller-manager
  annotations:
    numaflow.numaproj.io/description: A numaflow meta pipeline 
    numaflow.numaproj.io/owner: hq
    numaflow.numaproj.io/pipeline-name: nf-business-lineage-pipeline
    numaflow.numaproj.io/test: "true"
spec:
  watermark:
    idleSource:
      threshold: 30s
      incrementBy: 1s
      stepInterval: 1s
  templates:
    daemon:
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      imagePullSecrets:
        - name: github-docker-registry
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: eks.amazonaws.com/capacityType   #AWS
                operator: In
                values:
                - SPOT
          - weight: 1
            preference:
              matchExpressions:
              - key: lifecycle     #Azure
                operator: In
                values:
                - spot
          - weight: 1
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-provisioning  #GCP
                operator: In
                values:
                - spot          
    job:
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      imagePullSecrets:
        - name: github-docker-registry
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: eks.amazonaws.com/capacityType   #AWS
                operator: In
                values:
                - SPOT
          - weight: 1
            preference:
              matchExpressions:
              - key: lifecycle     #Azure
                operator: In
                values:
                - spot
          - weight: 1
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-provisioning  #GCP
                operator: In
                values:
                - spot
    # If using custom service accounts, set vertex to null
    vertex: null
    sideInputsManager:
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      imagePullSecrets:
        - name: github-docker-registry
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: eks.amazonaws.com/capacityType   #AWS
                operator: In
                values:
                - SPOT
          - weight: 1
            preference:
              matchExpressions:
              - key: lifecycle     #Azure
                operator: In
                values:
                - spot
          - weight: 1
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-provisioning  #GCP
                operator: In
                values:
                - spot     
  vertices:
    - name: bl-cdc-source
      source:
        kafka:
          brokers:
            - kafka-headless.kafka.svc.cluster.local:9092
          topic: DATA_MESH
          consumerGroup: nf-pipeline-bl-execution
          tls: null
          sasl: null
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      tolerations:
        - key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot
          effect: NoSchedule
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: eks.amazonaws.com/capacityType   #AWS
                operator: In
                values:
                - SPOT
          - weight: 1
            preference:
              matchExpressions:
              - key: lifecycle     #Azure
                operator: In
                values:
                - spot
          - weight: 1
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-provisioning  #GCP
                operator: In
                values:
                - spot            
      imagePullSecrets:
        - name: github-docker-registry
      scale:
        min: 1
        max: 1
    - name: bl-cdc-processor
      udf:
        container:
          image: ghcr.io/hq/image
          command:
            - ./main
            - execute
            - business-lineage-runner
          env:
            - name: HOST
              value: http://service.svc.cluster.local
            - name: ADDRESS
              value: http://service.svc.cluster.local
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: creds
                  key: creds
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name:creds
                  key: password
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: REDIS_HOST
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: redis-backup-secret
                  key: REDIS_PASSWORD
            - name: REDIS_PORT
              value: ""
            - name: PRODUCT_DNS
              valueFrom:
                secretKeyRef:
                  name: instance-domain-name
                  key: DOMAIN_NAME
                  optional: false
            - name: LD_SDK_KEY
              valueFrom:
                secretKeyRef:
                  name: launch-darkly-secret-parameter-store
                  key: USER_LAUNCH_DARKLY_SDK_KEY
                  optional: false
          resources: {}
        groupBy: 
          window:
            fixed:
              length: 60s
          keyed: true
          storage:
            persistentVolumeClaim:
              volumeSize: 1Gi
              accessMode: ReadWriteOnce 
        builtin: null
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      tolerations:
        - key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot
          effect: NoSchedule
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: eks.amazonaws.com/capacityType   #AWS
                operator: In
                values:
                - SPOT
          - weight: 1
            preference:
              matchExpressions:
              - key: lifecycle     #Azure
                operator: In
                values:
                - spot
          - weight: 1
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-provisioning  #GCP
                operator: In
                values:
                - spot            
      imagePullSecrets:
        - name: github-docker-registry
      serviceAccountName: numaflow-sa-default-ns
    - name: bl-dlq-sink
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      imagePullSecrets:
        - name: github-docker-registry
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: eks.amazonaws.com/capacityType   #AWS
                operator: In
                values:
                - SPOT
          - weight: 1
            preference:
              matchExpressions:
              - key: lifecycle     #Azure
                operator: In
                values:
                - spot
          - weight: 1
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-provisioning  #GCP
                operator: In
                values:
                - spot
      sink:
        kafka:
          brokers:
            - "kafka-broker"
          topic: "BUSINESS_LINEAGE_DLQ"
      scale:
        disabled: false
        min: 1
        max: 1

        
  edges:
    - from: bl-cdc-source
      to: bl-cdc-processor
      conditions: null
    - from: bl-cdc-processor
      to: bl-dlq-sink
      conditions:
        tags:
          values:
            - DLQ
```
