### ISSUE TITLE
Raptor generates wrong processing rate when multi-partition isb enabled

### ISSUE THREAD

**Issue by KeranYang** [numaproj/numaflow#1026]
**Describe the bug**
Expecting source vertex and sink vertex to have close processing rate but not. The issue emerges when I specify partitions for the sink vertex.

![Screenshot 2023-09-08 at 1 03 53 PM](https://github.com/numaproj/numaflow/assets/13165977/adb1f5c3-ab78-40e9-bed6-c08ddb2f66b4)

**To Reproduce**
Use the following template to deploy the pipeline.

```
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: multi-partition-pipeline
spec:
  templates:
    daemon:
      containerTemplate:
        env:
          - name: NUMAFLOW_DEBUG
            value: "true" # DO NOT forget the double quotes!!!
  vertices:
    - name: in
      scale:
        min: 5
      source:
        # A self data generating source
        generator:
          msgSize: 1
          rpu: 1
          duration: 1s
    - name: out
      partitions: 5
      scale:
        min: 5
      sink:
        # A simple log printing sink
        log: {}
  edges:
    - from: in
      to: out

```
