### ISSUE TITLE
Sink Vertex with SideInput always pending

### ISSUE THREAD

**Issue by jy4096** [numaproj/numaflow#1160]
kind local cluster
<img width="1304" alt="image" src="https://github.com/numaproj/numaflow/assets/19543684/05c98dc6-e7b6-411c-b342-5ac9fa754270">

example pipeline spec
```yaml
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  sideInputs:
    - name: myticker
      container:
        image: "quay.io/numaio/numaflow-go/sideinput-example:v0.5.0"
        imagePullPolicy: Always
      trigger:
        schedule: "*/2 * * * *"
        # timezone: America/Los_Angeles
    - name: mypicker
      container:
        image: "quay.io/numaio/numaflow-go/sideinput-example:v0.5.0"
        imagePullPolicy: Always
      trigger:
        schedule: "*/2 * * * *"
        # timezone: America/Los_Angeles
  vertices:
    - name: in
      source:
        # A self data generating source
        generator:
          rpu: 1
          duration: 1s
    - name: si-log
      udf:
        container:
          image: "quay.io/numaio/numaflow-go/udf-sideinput-example:v0.5.0"
          imagePullPolicy: Always
      containerTemplate:
        env:
          - name: NUMAFLOW_DEBUG
            value: "true" # DO NOT forget the double quotes!!!
      sideInputs:
        - myticker
    - name: even-or-odd
      scale:
        min: 1
      udf:
        container:
          # Tell the input number is even or odd, see https://github.com/numaproj/numaflow-go/tree/main/pkg/function/examples/even_odd
          image: quay.io/numaio/numaflow-go/map-even-odd:v0.5.0
      sideInputs:
        - myticker
        - mypicker
    - name: even-sink
      scale:
        min: 1
      sink:
        # A simple log printing sink
        log: { }
    - name: odd-sink
      scale:
        min: 1
      sink:
        log: { }
    - name: number-sink
      scale:
        min: 1
      sink:
        log: { }
      sideInputs:
        - mypicker
  edges:
    - from: in
      to: si-log
    - from: si-log
      to: even-or-odd
    - from: even-or-odd
      to: even-sink
      conditions:
        tags:
          operator: or
          values:
            - even-tag
    - from: even-or-odd
      to: odd-sink
      conditions:
        tags:
          operator: or
          values:
            - odd-tag
    - from: even-or-odd
      to: number-sink
      conditions:
        tags:
          operator: or
          values:
            - odd-tag
            - even-tag
```
