### ISSUE TITLE
Source transformer should progress the watermark even if the data is filtered by source-transformer

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#1357]
# Summary

We should publish and progress via WMB with idle=true even if the data is dropped by the source-transformer.

**Comment by KeranYang** [comment]
### Reproducing the problem

Trying to reproduce using the following pipeline spec:

```
spec:
  vertices:
    - name: in
      source:
        generator:
          rpu: 5
          duration: 1s
          msgSize: 8
        transformer:
          builtin:
            name: filter
            kwargs:
              expression: 1 == 0
      scale: {}
    - name: cat
      udf:
        container: null
        builtin:
          name: cat
    - name: out
      sink:
        log: {}
  edges:
    - from: in
      to: cat
    - from: cat
      to: out
```

I observed that although all the messages are filtered out by the source transformer, we are still publishing idle watermarks.

![Screenshot 2023-11-19 at 9 51 11 PM](https://github.com/numaproj/numaflow/assets/13165977/f9514ecb-003c-4483-bd85-afb2f23bcc4f)

Looking into the source forwarder, I see that 1. When we [publish source watermarks](https://github.com/numaproj/numaflow/blob/main/pkg/sources/forward/data_forward.go#L285), the messages dropped by source transformers are also counted, and 2. When we [publish an idle watermark](https://github.com/numaproj/numaflow/blob/main/pkg/sources/forward/data_forward.go#L371) for an idle out edge, we publish the source watermark of the read batch. Hence, we are progressing the watermark even if the data is filtered by source transformer.



Did I miss anything? (I assumed source idling is NOT part of this problem)
