### ISSUE TITLE
Source and UDF keeps restarting when scaled back to zero.

### ISSUE THREAD

**Issue by QuentinFAIDIDE** [numaproj/numaflow#1503]
**Describe the bug**
I have the following vertex set to be scaled to zero in some pipeline:
```yaml
name: cluster-tx-filter
udf:
  container:
    image: registry.gitlab.com/XXXX/my-monorepo/my-udf:v1.43.0
    env:
      - name: A_HANDFULL_OF_ENVARS
        value: "32"
    resources: {}
  builtin: null
  groupBy: null
metadata:
  annotations:
    numaflow.numaproj.io/map-stream: "true"
imagePullSecrets:
  - name: registry-credentials
limits:
  readBatchSize: 1
  readTimeout: 1h0m0s
scale:
  min: 0
  max: 0
```
It might be expected behavior, but while my will is respected for some time, there is a moment where the pipeline operator decides to start and stop the vertex with 1 replica, as the metrics in prometheus show:
![image](https://github.com/numaproj/numaflow/assets/3892217/d823c5df-638f-4e78-8963-330b9b7866a6)

**To Reproduce**

1. Scale a vertex in a pipeline to zero
2. Wait for some time
3. Eventually spam jetstream buffers with messages so that its start timing out here and there in other vertices (not sure if related).

**Expected behavior**
The pod should not start and stop in a loop.

**Environment (please complete the following information):**

- Kubernetes: v1.26.1+k3s1
- Numaflow: v1.1.4

**Additional context**

The pipeline where it happens has issues in the vertices closer to the source with Jetstream creating lots of network traffic and timing out, making it quite slow (pretty much a stall), even after switching it to memory storage. 
I also tried to scale some source before scaling down the UDF, but it had the same issue and as it was emitting some message for safety at startup, the messages sort of stacked up in front of the UDF I'm trying to keep scaled at zero.

I'd be happy to provide more context if required.

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.
