### ISSUE TITLE
Failed to incorporate affinity into vertex definition

### ISSUE THREAD

**Issue by lanedd** [numaproj/numaflow#1507]
**Describe the bug**
Can not introduce affinity definition into a vertex.  Instead I get an error message, "Failed sync attempt to 686e31f5b5f56d5f59a96a6eb908f48820e3bf36: one or more objects failed to apply (dry run) (retried 5 times)."

**To Reproduce**

1. Add an affinity section to a working pipeline vertex
```
spec:
  vertices:
    - name: vertex-name
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: numaflow.numaproj.io/vertex-name
                    operator: In
                    values:
                      - vertex-name
              topologyKey: kubernetes.io/hostname
```
2. Deploy updated pipeline

**Expected behavior**
I expected the pipeline to redeploy with a pod anti affinity that would discourage pods with the same vertex-name from deploying on the same pod.

**Screenshots**
![image](https://github.com/numaproj/numaflow/assets/43617392/b0176f18-de94-4fe1-8bfd-7032384b0e3c)

**Environment (please complete the following information):**

- Kubernetes: v1.20.7
- Numaflow: 1.0.0

**Additional context**
I suspected but wasn't sure that `(Members of AbstractPodTemplate are embedded into this type.)` meant the keys of AbstractPodTemplate were embedded into the vertex definition so I also tried:
```
spec:
  vertices:
    - name: vertex-name
      AbstractPodTemplate:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: numaflow.numaproj.io/vertex-name
                      operator: In
                      values:
                        - vertex-name
                topologyKey: kubernetes.io/hostname
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.
