### ISSUE TITLE
Numaflow UI: Need better pipeline representation for complex pipeline

### ISSUE THREAD

**Issue by sarabala1979** [numaproj/numaflow#1547]
**Describe the bug**
<img width="1255" alt="image" src="https://github.com/numaproj/numaflow/assets/33908564/2a456627-6c04-41ff-a8c6-f225d331323e">

Edges:
```yaml
  edges:
    - from: input
      to: window
    - from: input
      to: input-output
    - from: window
      to: win-out
    - from: window
      to: preprocess
    - from: preprocess
      to: inference
      conditions:
        tags:
          operator: or
          values:
            - inference
    - from: preprocess
      to: staticthresh
      conditions:
        tags:
          operator: or
          values:
            - staticthresh
    - from: preprocess
      to: trainer
      conditions:
        tags:
          operator: or
          values:
            - train
    - from: inference
      to: postprocess
      conditions:
        tags:
          operator: or
          values:
            - postprocess
    - from: inference
      to: trainer
      conditions:
        tags:
          operator: or
          values:
            - train
    - from: inference
      to: staticthresh
      conditions:
        tags:
          operator: or
          values:
            - staticthresh
    - from: postprocess
      to: prom-pusher
    - from: postprocess
      to: trainer
      conditions:
        tags:
          operator: or
          values:
            - train
      onFull: discardLatest
    - from: postprocess
      to: staticthresh
      conditions:
        tags:
          operator: or
          values:
            - staticthresh
    - conditions:
        tags:
          operator: or
          values:
            - output
      from: postprocess
      to: output
    - from: staticthresh
      to: prom-pusher
    - from: staticthresh
      to: output
    - from: trainer
      to: trainer-out
```

**To Reproduce**

1. ....
2. ....
3. ....

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- Kubernetes: [e.g. v1.18.6]
- Numaflow: [e.g. v0.5.1]

**Additional context**

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

>For quick help and support, join our [slack](https://numaproj.slack.com/join/shared_invite/zt-19svuv47m-YKHhsQ~~KK9mBv1E7pNzfg#/shared-invite/email) channel.
