### ISSUE TITLE
ReduceStreamer: `Server info file /var/run/numaflow/reducer-server-info is not ready`

### ISSUE THREAD

**Issue by th0ger** [numaproj/numaflow#1665]
**Describe the bug**

I'm testing the ReduceStreamer rc in python.
The reduce vertex keeps receiving data in the isb, but no output.
Numa keeps logging `Server info file /var/run/numaflow/reducer-server-info is not ready`. What does this mean?

My reducer example is sliding window with length: 60s / slide: 10s, and emitting each datum directly to NonBlockingIterator.

**To Reproduce**
Relevant code snippets:

```python
from collections.abc import AsyncIterable

from pynumaflow.reducestreamer import Message, Datum, Metadata, ReduceStreamAsyncServer, ReduceStreamer
from pynumaflow.shared.asynciter import NonBlockingIterator
import json

class ReduceCounter(ReduceStreamer):
    def __init__(self, counter):
        print("ReduceCounter init")
        self.counter = counter

    async def handler(
        self,
        keys: list[str],
        datums: AsyncIterable[Datum],
        output: NonBlockingIterator,
        md: Metadata,
    ):
        print("ReduceCounter handler")
        async for _ in datums:
            print("ReduceCounter async")
            self.counter = 1
            msg = json.dumps({
                "count": self.counter,
            })
            await output.put(Message(str.encode(msg), keys=keys))

if __name__ == "__main__":
    print("Starting processor1")
    grpc_server = ReduceStreamAsyncServer(ReduceCounter, init_args=(0,))
    grpc_server.start()
```

```yaml
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-vibrationsensor
spec:
  vertices:
    # Pipeline input
    - name: in
      scale:
        min: 1
      source:
        kafka:
          brokers:
            - kafka-broker:9092
          topic: mytopic
          consumerGroup: my-consumer-group
        transformer:
          builtin:
            name: eventTimeExtractor
            kwargs:
              expression: sprig.trim(string(json(payload).timestamp))
    # Process
    - name: reduce-sliding
      partitions: 1
      udf:
        container:
          image: processor1:local
        groupBy:
          window:
            sliding:
              length: 60s
              slide: 10s
          keyed: false
          storage:
            persistentVolumeClaim:
              volumeSize: 10Gi
              accessMode: ReadWriteOnce
      containerTemplate:
        env:
          - name: NUMAFLOW_DEBUG
            value: "true" # DO NOT forget the double quotes!!!
    # Display the aggregated info in the log
    - name: log-output
      scale:
        min: 1
      sink:
        log: {}
  edges:
    - from: in
      to: reduce-sliding
    - from: reduce-sliding
      to: log-output
```

**Expected behavior**
One async event outputted per input when processing the window.

**Screenshots**
![image](https://github.com/numaproj/numaflow/assets/26322144/a55e49f3-5316-4903-891a-b9cfea6e7722)

**Environment (please complete the following information):**

- Kubernetes: kind version 0.22.0
- Numaflow: v1.2.0-rc3
- pynumaflow: 0.7.0a0

**Additional context**
numa logs:
```
Loading logs...
2024-04-13T14:41:17.432598047Z INFO numaflow.ReduceUDF-processor commands/processor.go:48 Starting vertex data processor {"version": "Version: v1.2.0-rc3, BuildDate: 2024-04-09T04:15:55Z, GitCommit: 4e172e808d31659b2364088d8a07fcf6381d4040, GitTag: v1.2.0-rc3, GitTreeState: clean, GoVersion: go1.21.9, Compiler: gc, Platform: linux/amd64"}
2024/04/13 14:41:17 Server info file /var/run/numaflow/reducer-server-info is not ready...
2024/04/13 14:41:18 Server info file /var/run/numaflow/reducer-server-info is not ready...
2024/04/13 14:41:19 Server info file /var/run/numaflow/reducer-server-info is not ready...
2024/04/13 14:41:20 Server info file /var/run/numaflow/reducer-server-info is not ready...
(keeps posting)
```
udf logs:
```
Loading logs...
+ python main.py
Starting processor1
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

>For quick help and support, join our [slack](https://numaproj.slack.com/join/shared_invite/zt-19svuv47m-YKHhsQ~~KK9mBv1E7pNzfg#/shared-invite/email) channel.
