### ISSUE TITLE
MonoVertex gets autoscaled to zero replicas when the pending is zero and processing rate is not zero

### ISSUE THREAD

**Issue by yhl25** [numaproj/numaflow#1960]
**Describe the bug**
MonoVertex gets autoscaled to zero replicas when the pending is zero and the processing rate is not zero

**To Reproduce**

* Create a monovertex with the udsource that returns pending as zero and the read rate is non zero

**Expected behavior**
Since the processing rate is not zero, it should not autoscale to zero replicas.

**Comment by kohlisid** [comment]
Can you share the spec that you used?

I tried with our example spec and latest main and was seeing the field getting populated. 

Maybe was there any other steps that I'm missing here. Or should I wait for some more time etc?


```
spec:
  replicas: 1
  sink:
    udsink:
      container:
        image: quay.io/numaio/numaflow-java/simple-sink:stable
  source:
    transformer:
      container:
        image: quay.io/numaio/numaflow-rs/source-transformer-now:stable
    udsource:
      container:
        image: quay.io/numaio/numaflow-java/source-simple-source:stable
```

```
{
  "metrics": {
    "monoVertex": "simple-mono-vertex",
    "processingRates": {
      "15m": 16117.8571428571,
      "1m": 16091.6666666667,
      "5m": 16117.8571428571,
      "default": 16133.3333333333
    },
    "pendings": {
      "15m": "0",
      "1m": "0",
      "5m": "0",
      "default": "0"
    }
  }
}
```
