### ISSUE TITLE
Suspected Memory leak on JetStream

### ISSUE THREAD

**Issue by qianbeibuzui** [numaproj/numaflow#2241]
I'm very sorry to bother you again. I seem to have encountered a memory leak situation.
I continue to conduct stress tests on numaflow using TPS: 7000. Based on my continuous observation of the "isbsvc default js-x)" pod, the memory keeps rising until an Error (OOMKilled) occurs.
As shown in the figure:
![image](https://github.com/user-attachments/assets/1e4ce638-ba50-4511-894f-43a12f2bbbfa)
![image](https://github.com/user-attachments/assets/36895b0c-5a7d-4370-9bb9-93f67356b12e)

This is my InterStepBufferService setting:

```
kind: InterStepBufferService
apiVersion: numaflow.numaproj.io/v1alpha1
metadata:
  name: default
  namespace: default
spec:
  jetstream:
    version: latest
    replicas: 3
    containerTemplate:
      resources:
        limits:
          cpu: "4"
          memory: 8Gi
    persistence:
      storageClassName: cbs
      volumeSize: 100Gi
    bufferConfig: |
      stream:
        # 0: Limits, 1: Interest, 2: WorkQueue
        retention: 0
        maxMsgs: 50000
        maxAge: 24h
        maxBytes: -1
        # 0: File, 1: Memory
        storage: 0         ### <- this switch to RAM only mode
        replicas: 3        ### <- this does not replicate data in the streams
        duplicates: 15m
  config:
    jetstream:
      streamConfig: |
        stream:
          duplicates: 15m
          maxage: 24h
          maxbytes: -1
          maxmsgs: 50000
          replicas: 3
          retention: 0
          storage: 0
  type: jetstream
```

This is my Pipeline setting:

```
kind: Pipeline
apiVersion: numaflow.numaproj.io/v1alpha1
metadata:
  name: bi-device-pipeline
  namespace: default
spec:
  vertices:
    - name: in
      source:
        kafka:
          brokers:
            - 10.0.2.224:9092
          topic: ad_pool_shiyuegame_com.device
          consumerGroup: huijuan-consumer-group-device
          tls: null
          config: >
            consumer:
              offsets:
                initial: -2 # -2 for sarama.OffsetOldest, -1 for sarama.OffsetNewest. Default to sarama.OffsetNewest.
          sasl: null
          kafkaVersion: 2.8.1
      containerTemplate:
        resources:
          limits:
            cpu: 300m
            memory: 322122547200m
          requests:
            cpu: 300m
            memory: 322122547200m
      imagePullSecrets:
        - name: fxzc-image
      scale:
        min: 1
        max: 1
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
    - name: device
      udf:
        container:
          image: xx/device_mapper:latest
          resources: {}
        builtin: null
        groupBy: null
      containerTemplate:
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
      imagePullSecrets:
        - name: fxzc-image
      limits:
        readBatchSize: 5000
        readTimeout: 30s
        bufferMaxLength: 20000
        bufferUsageLimit: 85
      scale:
        min: 1
        max: 1
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
    - name: starrocks
      sink:
        udsink:
          container:
            image: xx/starrocks_sink:latest
            resources: {}
        retryStrategy: {}
      containerTemplate:
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
      imagePullSecrets:
        - name: fxzc-image
      limits:
        readBatchSize: 5000
        readTimeout: 30s
        bufferMaxLength: 20000
        bufferUsageLimit: 85
      scale:
        min: 1
        max: 1
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
  edges:
    - from: in
      to: device
      conditions: null
      onFull: retryUntilSuccess
    - from: device
      to: starrocks
      conditions: null
      onFull: retryUntilSuccess
  lifecycle:
    deleteGracePeriodSeconds: 30
    desiredPhase: Running
    pauseGracePeriodSeconds: 30
  limits:
    readBatchSize: 1000
    bufferMaxLength: 20000
    bufferUsageLimit: 85
    readTimeout: 30s
  watermark:
    maxDelay: 0s
  templates:
    daemon:
      imagePullSecrets:
        - name: fxzc-image
    job:
      imagePullSecrets:
        - name: fxzc-image
    sideInputsManager:
      imagePullSecrets:
        - name: fxzc-image
status:
  conditions:
    - type: Configured
      status: "True"
      lastTransitionTime: 2024-11-27T10:48:02Z
      reason: Successful
      message: Successful
    - type: DaemonServiceHealthy
      status: "True"
      lastTransitionTime: 2024-11-27T10:48:02Z
      reason: Successful
      message: Successful
    - type: Deployed
      status: "True"
      lastTransitionTime: 2024-11-27T10:48:02Z
      reason: Successful
      message: Successful
    - type: SideInputsManagersHealthy
      status: "True"
      lastTransitionTime: 2024-11-27T10:48:02Z
      reason: NoSideInputs
      message: No Side Inputs attached to the pipeline
    - type: VerticesHealthy
      status: "True"
      lastTransitionTime: 2024-11-27T10:48:02Z
      reason: Successful
      message: All vertices are healthy
  phase: Running
  lastUpdated: 2024-11-27T10:48:02Z
  vertexCount: 3
  sourceCount: 1
  sinkCount: 1
  udfCount: 1
  mapUDFCount: 1
  reduceUDFCount: 0
  observedGeneration: 4
```

numaflow:v1.4.0
k8s:v1.24.4
nats:2.10.17

_Originally posted by @qianbeibuzui in https://github.com/numaproj/numaflow/discussions/2239#discussioncomment-11397240_
