### ISSUE TITLE
Why is the data read by User defined Sinks out of order? The default is out of order? Is there any way to become orderly?

### ISSUE THREAD

**Issue by qianbeibuzui** [numaproj/numaflow#2246]
**The order of entering BatchMapFn and Sink is inconsistent,
The data is out of order after reaching Sink.**

```
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: bi-account-pipeline-v2
spec:
  templates:
    daemon:
      imagePullSecrets:
    job:
      imagePullSecrets:
        - name: fxzc-image
    sideInputsManager:
      imagePullSecrets:
        - name: fxzc-image
  limits:
    readBatchSize: 1000
    bufferMaxLength: 20000
    bufferUsageLimit: 85
    readTimeout: 30s
  vertices:
    - name: in
      containerTemplate:
        resources:
          limits:
            cpu: "0.2"
            memory: 0.2Gi
          requests:
            cpu: "0.2"
            memory: 0.2Gi
      imagePullSecrets:
        - name: fxzc-image
      scale:
        min: 1
        max: 1
      source:
        kafka:
    - name: account
      limits:
        readBatchSize: 5000
        bufferMaxLength: 20000
        bufferUsageLimit: 85
        readTimeout: 30s
      imagePullSecrets:
        - name: fxzc-image
      scale:
        min: 1
        max: 1
      udf:
        container:
          image: xxx:latest # use  BatchMapFn
    - name: starrocks
      containerTemplate:
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 1Gi
      limits:
        readBatchSize: 5000
        bufferMaxLength: 20000
        bufferUsageLimit: 85
        readTimeout: 60s
      imagePullSecrets:
        - name: fxzc-image
      scale:
        min: 1
        max: 1
      sink:
        udsink:
          container:
            image: xxx:latest
  edges:
    - from: in
      to: account
      onFull: retryUntilSuccess
    - from: account
      to: starrocks
      onFull: retryUntilSuccess
```

- Kubernetes: v1.24.4
- Numaflow:  v1.4
- GoSdk：github.com/numaproj/numaflow-go v0.9.0
