### ISSUE TITLE
Implement Aggregation/Reduce feature

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#231]
Ability to implement stream aggregation or reduction by providing user-defined functions.

```yaml
spec:
  vertices:
    - name: reduce-by-key
      udf:
        container:
          image:sum-by-key:latest
        groupby:
           window:
             fixed:
               length: 1m # 1 minute
           # if true, then it is a keyed stream, else it is non-keyed.
           keyed: true # can be false too
```

- [x] #208 
- [x] #233
- [x] #234
- [x] #339
- [x] #201 
- [x] #246
- [x] #289
- [x] #291
- [x] #292 
- [x] #373
- [x] #301
- [x] Integrate with WAL
  - [x] #343 
  - [x] #293 
- [x] #313
- [x] #338
- [x] #237
- [x] SDK Support for reduce
  - [x] Golang
  - [x] [Python](https://github.com/numaproj/numaflow-python/pull/40)
  - [x] [Java](https://github.com/numaproj/numaflow-java/pull/4)
- [x] FMEA
- [x] #403
  - [x] user guide
  - [x] example pipelines
- [x] Blog for reduce
