### ISSUE TITLE
Pipeline never drains when paused

### ISSUE THREAD

**Issue by juliev0** [numaproj/numaflow#2396]
**Describe the bug**

This happens every time when I create this pipeline and then set its desiredPhase=Paused:

```
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: my-pipeline
  namespace: example-namespace
spec:
  interStepBufferServiceName: my-isbsvc-1
  vertices:
    - name: in
      scale:
        min: 3
        max: 6
      source:
        udsource:
          container:
            image: quay.io/numaio/numaflow-go/source-simple-source:stable
    - name: out
      sink:
        log: {}
  edges:
    - from: in
      to: out
```

It does get to "Paused" but it never sets "drainedOnPause: true".

Note that there is no data coming into the pipeline, so it may be specific to a case of no data. (I know a previous [bug](https://github.com/numaproj/numaflow/issues/2331) was [resolved](https://github.com/numaproj/numaflow/pull/2346) by @whynowy that was related to no data, so I'm not sure if this issue would be fixed by that.)

I am running Numaflow 1.4.2.

**To Reproduce**

1. create pipeline shown above
2. set `lifecycle.desiredPhase=Paused`
3. observed that Pipeline Status shows `phase=Paused` but not `drainedOnPause=true`

This zip file contains numaflow controller log as well as result pipeline:
[Archive 4.zip](https://github.com/user-attachments/files/18815655/Archive.4.zip)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

>For quick help and support, join our [slack](https://numaproj.slack.com/join/shared_invite/zt-19svuv47m-YKHhsQ~~KK9mBv1E7pNzfg#/shared-invite/email) channel.
