### ISSUE TITLE
Regression (numaflow 1.4.3 RC2): Pipeline never marked "drainedOnPause: true"

### ISSUE THREAD

**Issue by juliev0** [numaproj/numaflow#2413]
**Describe the bug**

Numaplane e2e is failing at the part in which we explicitly set `desiredPhase: Paused` in the PipelineRollout, which sets it in the `Pipeline`. 

Pipeline gets to "Paused" but "drainedOnPause" is not set.

I was able to reproduce this. Create this Pipeline and then set its `lifecycle.desiredPhase=Paused`:

```
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  labels:
    numaplane.numaproj.io/isbsvc-child-name: test-isbservice-rollout-0
    numaplane.numaproj.io/isbsvc-name: test-isbservice-rollout
    numaplane.numaproj.io/parent-rollout-name: test-pipeline-rollout
    numaplane.numaproj.io/upgrade-state: promoted
  name: test-pipeline-reproduce-0
  namespace: numaplane-system
spec:
  edges:
  - conditions: null
    from: in
    to: cat
  - conditions: null
    from: cat
    to: out
  interStepBufferServiceName: test-isbservice-rollout-0
  lifecycle:
    deletionGracePeriodSeconds: 10
  vertices:
  - name: in
    scale:
      max: 1
      min: 1
      zeroReplicaSleepSeconds: 15
    source:
      generator:
        duration: 1s
        rpu: 5
    updateStrategy: {}
  - name: cat
    scale:
      max: 1
      min: 1
      zeroReplicaSleepSeconds: 15
    udf:
      builtin:
        name: cat
      container: null
      groupBy: null
    updateStrategy: {}
  - name: out
    scale:
      max: 1
      min: 1
      zeroReplicaSleepSeconds: 15
    sink:
      log: {}
      retryStrategy: {}
    updateStrategy: {}
  watermark: {}

``` 

Reference to where it failed in Numaplane CI: https://github.com/numaproj/numaplane/actions/runs/13449066431/job/37580191564?pr=590

[numaflow-controller-9dd744855-2qzcd-controller-manager.log.zip](https://github.com/user-attachments/files/18900628/numaflow-controller-9dd744855-2qzcd-controller-manager.log.zip)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

>For quick help and support, join our [slack](https://numaproj.slack.com/join/shared_invite/zt-19svuv47m-YKHhsQ~~KK9mBv1E7pNzfg#/shared-invite/email) channel.
