### ISSUE TITLE
Auth Tokens from Trusted Peers break Dex auth client

### ISSUE THREAD

**Issue by garretthaney** [numaproj/numaflow#2459]
**Describe the bug**
If a token generated by a trusted peer is used, the Dex client breaks when attempting to unmarshall the token into Numaflow's own internal class. 

The token will properly validate through all the code utilizing the oidc library code, but break when attempting to unmarshall here:
https://github.com/numaproj/numaflow/blob/main/server/apis/v1/dexauthn.go#L120

The audience field of the ID Token from Dex can be either a string, or an array of strings, but the internal definition declares it to be a string:
https://github.com/numaproj/numaflow/blob/main/server/authn/user_info.go#L23

The token from the trusted peer will have both the originating client and the target client in the audience flag, making the audience field an array of strings for a trusted peer token.

See, for reference:
https://github.com/coreos/go-oidc/blob/v3/oidc/oidc.go#L423

Changing Numaflow's definition of "Aud" field to from string -> any seems to resolve the issue and allow authentication from either the main Numaflow UI staticClient or the trusted peer, but perhaps a better solution would be to implement an array of strings with a custom unmarshaller similar to the oidc code.

**To Reproduce**
Example client and connector dex configuration for Dex server:
```
staticClients:
  - id: numaflow-server-app
    redirectURIs:
      # URI of the application login endpoint
      - https://yournumaserver/login
    name: 'Numaflow Server App'
    public: true
    trustedPeers:
      - numaflow-mmi
  - id: numaflow-mmi
    secret: my-secret
    name: 'Numaflow Server MMI'
    public: true

connectors:
  - type: oidc
    id: keycloak
    name: keycloak
    config:
      # CA of the authentication endpoint
      rootCA: /etc/ssl/certs/tls.crt
      # Keycloak endpoint that issues the token for the desired realm
      issuer: https://yourkeycloak/realms/YOURREALM
      # where to return once authenticated
      redirectURI: https://yournumaserver/dex/callback
      # client ID of the keycloak connector
      clientID: $KEYCLOAK_CLIENT_ID
      # UUID of the keycloak connector
      clientSecret: $KEYCLOAK_CLIENT_SECRET
      # enable reading groups from the provided token
      # can become stale if groups of a user are changed between refreshes
      insecureEnableGroups: true
      getUserInfo: true
```
1.) Get keycloak token from upstream IDP e.g. -
```
keycloak_id = keycloak.openid_connection.KeycloakOpenID(server_url=keycloak_url,realm_name=realm,client_id=client_id,client_secret_key=client_secret)`
token = keycloak_id.token(username,password)
keycloak_token = token["access_token"]
```
2.) Exchange upstream token for dex id token, targeting machine interface in dex.
```
token_endpoint = f"{self.dex_url}/token"
data = {
            "grant_type":  "urn:ietf:params:oauth:grant-type:token-exchange" ,
            "subject_token": keycloak_token ,
            "subject_token_type": "urn:ietf:params:oauth:token-type:access_token",
            "scope": "openid groups federated:id audience:server:client_id:numaflow-server-app", #Important thing is the audience for numaflow's dex client
            "connector_id": "keycloak",
            "client_id": "numaflow-mmi",
            "requested_token_type": "urn:ietf:params:oauth:token-type:id_token" #access_token should also work
        }
dex_response = requests.post(token_endpoint, auth=(client_id,client_secret),data=data,verify=False)
dex_token_response = dex_response.json()["access_token"]
```
3.) Try to do an authenticated numaflow API call:

```python
url = ANY_API_TARGET
id_cookie = f"1:{{\"id_token\":\"{dex_token_response}\"}}"
should_work = urllib.parse.quote(id_cookie)
response = session.get( url, timeout=3,
                        cookies={"numaflow.token": should_work,
                                "numaflow-login": "dex"
                                },
                        verify=False
                      )
```
Token gets through authentication code in dex client, but won't unmarshall.

**Expected behavior**
Token should authenticate and API call should succeed.

**Screenshots**

**Environment (please complete the following information):**

- Kubernetes: v1.24.17+rke2r1
- Numaflow: v1.4.2 (also tested on `894674675834428c1148ac2ff190094337a74c89 refs/heads/main`)

**Additional context**
Running numaflow w/ dex authentication using upstream keycloak server.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

>For quick help and support, join our [slack](https://numaproj.slack.com/join/shared_invite/zt-19svuv47m-YKHhsQ~~KK9mBv1E7pNzfg#/shared-invite/email) channel.
