### ISSUE TITLE
Support Reduce Vertex

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#246]
We need to support reduce vertex for distributed aggregation, which is an extension of `UDF`. This will introduce `windows` and `group-by-key`.

```yaml
spec:
  vertices:
    - name: sum-by-key
      udf:
        container:
          image:sum-by-key:latest
        groupby:
           window:
             fixed:
               length: 1m # 1 minute
           # if true, pass the key as-is, else replace key with “”
           keyed: true | false  
           parallelism: 10

```

The output record for a non-keyed stream with have key set to `ALL`.
