### ISSUE TITLE
Pipeline doesn't successfully pause if Vertex has 0 Pods to begin with

### ISSUE THREAD

**Issue by juliev0** [numaproj/numaflow#2535]
**Describe the bug**

**To Reproduce**

1. Create a Pipeline like this:
```
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: my-generator-pipeline
spec:
  lifecycle:
    pauseGracePeriodSeconds: 60
  interStepBufferServiceName: my-isbsvc
  vertices:
    - name: in
      scale:
        min: 4
        max: 5
      source:
        generator:
          rpu: 5
          duration: 1s
    - name: cat
      scale: 
        min: 0
        max: 0
      udf:
        builtin:
          name: cat # A built-in UDF which simply cats the message
    - name: out
      scale:
        min: 1
        max: 1
      sink:
        log: {}
  edges:
    - from: in
      to: cat
    - from: cat
      to: out
```

2. Do `kubectl edit pipeline my-generator-pipeline` and set `lifecycle.desiredPhase: Paused`
3. Observe that it takes until `pauseGracePeriodSeconds=60` for the `out` vertex Pod to be deleted
4. Observe that `status.drainedOnPause` is never set to true

**Expected behavior**
`drainedOnPause` should be true. It shouldn't take until the pauseGracePeriodSeconds for it to pause with rpu so low.

Note: if I change the example above such that cat vertex has min=max=1, everything works as expected.

**Environment (please complete the following information):**

Numaflow version: 1.4.4

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

>For quick help and support, join our [slack](https://numaproj.slack.com/join/shared_invite/zt-19svuv47m-YKHhsQ~~KK9mBv1E7pNzfg#/shared-invite/email) channel.
