### ISSUE TITLE
Controller changes for supporting rust based builtin Kafka Sink

### ISSUE THREAD

**Issue by yhl25** [numaproj/numaflow#2597]

**Comment by BulkBeing** [comment]
Currently by adding this env variable, the Rust version is used:
```yaml
    - name: kafka-out
      containerTemplate:
        image:
        env:
          - name: NUMAFLOW_RUNTIME
            value: "rust"
```
