### ISSUE TITLE
serving pipeline spec in UI is not showing "serve" builtin

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#2617]
The real spec is
```yaml
      - name: out
        sink:
          serve: {}
```
but in the UI `serve` is missing.

<img width="1084" alt="Image" src="https://github.com/user-attachments/assets/c3c53b89-4165-479d-9319-e93006636d8d" />
