### ISSUE TITLE
Sink Retry Config not honoured in case of Pipeline in Rust

### ISSUE THREAD

**Issue by adarsh0728** [numaproj/numaflow#2637]
### Pipeline Spec

```
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  vertices:
    - name: in
      source:
        generator:
          rpu: 5
          duration: 1s
    - name: cat
      scale:
        min: 1
      udf:
        container:
          image: quay.io/numaio/numaflow-go/map-forward-message:stable
    - name: out
      containerTemplate:
        env:
          - name: NUMAFLOW_RUNTIME
            value: "rust"
      sink:
        retryStrategy:
          backoff:
            interval: 1s
            steps: 100
        udsink:
          container:
            image: quay.io/numaio/numaflow-go/sink-log:stable
            imagePullPolicy: Never
  edges:
    - from: in
      to: cat
    - from: cat
      to: out
```

### Logs for Config

```
2025-05-15T04:05:01.180025Z  INFO numaflow_core: Starting pipeline forwarder with config: PipelineConfig {
    pipeline_name: "simple-pipeline",
    vertex_name: "out",
    replica: 0,
    batch_size: 500,
    paf_concurrency: 1000,
    read_timeout: 1s,
    js_client_config: ClientConfig {
        url: "nats://isbsvc-default-js-svc.default.svc:4222",
        user: Some(
            "U1MgZuCz",
        ),
        password: Some(
            "FE7A6Sm4Z9lrywrk",
        ),
    },
    from_vertex_config: [
        FromVertexConfig {
            name: "cat",
            reader_config: BufferReaderConfig {
                streams: [
                    Stream {
                        name: "default-simple-pipeline-out-0",
                        vertex: "out",
                        partition: 0,
                    },
                ],
                wip_ack_interval: 1s,
            },
            partitions: 1,
        },
    ],
    to_vertex_config: [],
    vertex_type_config: Sink(
        SinkVtxConfig {
            sink_config: SinkConfig {
                sink_type: UserDefined(
                    UserDefinedConfig {
                        grpc_max_message_size: 67108864,
                        socket_path: "/var/run/numaflow/sink.sock",
                        server_info_path: "/var/run/numaflow/sinker-server-info",
                    },
                ),
                retry_config: None,
            },
            fb_sink_config: None,
            serving_store_config: None,
        },
    ),
    metrics_config: MetricsConfig {
        metrics_server_listen_port: 2469,
        lag_check_interval_in_secs: 5,
        lag_refresh_interval_in_secs: 3,
        lookback_window_in_secs: 120,
    },
    watermark_config: Some(
        Edge(
            EdgeWatermarkConfig {
                from_vertex_config: [
                    BucketConfig {
                        vertex: "cat",
                        partitions: 1,
                        ot_bucket: "default-simple-pipeline-cat-out_OT",
                        hb_bucket: "default-simple-pipeline-cat-out_PROCESSORS",
                    },
                ],
                to_vertex_config: [],
            },
        ),
    ),
    callback_config: None,
}
```
### Actual

`retry_config: None`

### Expected

`retry_config` should not be None whether it is configured or not in pipeline spec.
