### ISSUE TITLE
[Rust] Generator source is not decoding base64 encoded value blob

### ISSUE THREAD

**Issue by BulkBeing** [numaproj/numaflow#2737]
**Describe the bug**
User doc says to specify the content the Generator source sends to be in base64 format https://numaflow.numaproj.io/user-guide/sources/generator/#user-defined-data. However, we are not decoding the data https://github.com/numaproj/numaflow/blob/e06ce82e6d1eee343bac447ea62dadcbd9ecc10d/rust/numaflow-core/src/config/components.rs#L60

Noticed when testing Pulsar sink. 
```yaml
apiVersion: numaflow.numaproj.io/v1alpha1
kind: MonoVertex
metadata:
  name: simple-mono-vertex
spec:
  source:
    generator:
      rpu: 1
      duration: 1s
      valueBlob: "aGVsbG8gd29ybGQK"
  sink:
    pulsar:
      serverAddr: pulsar://host.lima.internal:6650
      topic: persistent://public/default/test-topic
      producerName: test-producer
```

The message that reaches to consumer that listens for data published by our pulsar sink:
```
publishTime:[1750302852939], eventTime:[0], key:[null], properties:[__key_len=0], content:aGVsbG8gd29ybGQK
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

>For quick help and support, join our [slack](https://numaproj.slack.com/join/shared_invite/zt-19svuv47m-YKHhsQ~~KK9mBv1E7pNzfg#/shared-invite/email) channel.
