### ISSUE TITLE
Rust: reduce with multiple partitions( fixed window ) in `CrashLoopBackOff` state

### ISSUE THREAD

**Issue by adarsh0728** [numaproj/numaflow#2764]
Spec: 

```
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: even-odd-sum
spec:
  vertices:
    - name: in
      containerTemplate:
        env:
          - name: NUMAFLOW_RUNTIME
            value: "rust"
      source:
        http: {}
    - name: atoi
      containerTemplate:
        env:
          - name: NUMAFLOW_RUNTIME
            value: "rust"
      scale:
        min: 3
      udf:
        container:
          # Tell the input number is even or odd, see https://github.com/numaproj/numaflow-go/tree/main/pkg/mapper/examples/even_odd
          image: quay.io/numaio/numaflow-go/map-even-odd:stable
    - name: compute-sum
      containerTemplate:
        env:
          - name: NUMAFLOW_RUNTIME
            value: "rust"
      udf:
        container:
          # compute the sum
          image: quay.io/numaio/numaflow-go/reduce-sum:stable
          imagePullPolicy: Always
        groupBy:
          window:
            fixed:
              length: 60s
          keyed: true
          storage:
            emptyDir: {}
      partitions: 3
    - name: sink
      containerTemplate:
        env:
          - name: NUMAFLOW_RUNTIME
            value: "rust"
      scale:
        min: 1
      sink:
        log: {}
  edges:
    - from: in
      to: atoi
    - from: atoi
      to: compute-sum
    - from: compute-sum
      to: sink
```

Numa Logs:

```
2025-06-30T14:37:32.845366Z INFO async_nats: event: closed
2025-06-30T14:37:32.833784Z ERROR numaflow::setup_tracing: /numaflow/numaflow-core/src/watermark/processor/manager.rs:267:40: index out of bounds: the len is 1 but the index is 2
2025-06-30T14:37:32.829504Z INFO async_nats: event: connected
2025-06-30T14:37:32.826127Z INFO numaflow_core::pipeline: Fence file "/var/numaflow/pbq/compute-sum-1" is now available
2025-06-30T14:37:32.824960Z INFO numaflow_core::pipeline: Starting reduce forwarder
```

<img width="909" alt="Image" src="https://github.com/user-attachments/assets/45679d57-4a4c-4a94-8a36-7f69597a4f6b" />
