### ISSUE TITLE
Default logs and exec to udf/udsink containers

### ISSUE THREAD

**Issue by dseapy** [numaproj/numaflow#283]
# Summary

Make it simpler for first-time numaflow SDK users to look at their container logs or exec into their containers by defaulting `kubectl logs` and `kubectl exec` to use their container.  A few options:

1. Move the `udsink` and `udf` containers to be before the `main` container in the pod container list
2. Set `kubectl.kubernetes.io/default-container` pod annotation in controller
3. Keep things as-is, but have users set the annotation in the examples (at least ones in sdk repos) to look like:
```yaml
  - name: forward-message
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: udf
    udf:
      container:
         ...
```
```yaml
    - name: out
      metadata:
        annotations:
          kubectl.kubernetes.io/default-container: udsink
      sink:
        udsink:
          container:
            ...
```

# Use Cases

When developing a function or sink using one of the numaflow SDKs I'm regularly wanting to look at my container's logs.  When doing this I have to remember to add `-c udf` or `-c udsink` to kubectl commands or I get unexpected logs.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
