### ISSUE TITLE
Support controller-wide HA Daemon configuration

### ISSUE THREAD

**Issue by dseapy** [numaproj/numaflow#331]
# Summary

#305 simplifies Pipeline yaml for daemon deployments for resources, replicas, annotations, etc.  However it's not particularly useful for anything requiring the pipeline-name (i.e. affinity's `labelSelector` or podDisruptionBudget's `matchLabels`).  `PodDisruptionBudget` being a bit different from affinity, since it's a separate resource that currently the controller doesn't manage.

Would be helpful to support configuring these things on the controller, maybe one of the following?:
1. Make `templates` go-templates that get parsed, and then in reconcile get `execute`'d with access to the Pipeline object, allowing user access to the pipeline resource (i.e. `numaflow.numaproj.io/pipeline-name: {{ .Pipeline.Name}}`)
2. Support a way to specify affinity and podDisruptionBudgets on the Pipeline that doesn't get directly passed through to the pod.

PodDisruptionBudgets would need to be owned by the Pipeline resource and managed by the controller.

# Use Cases

Avoid needing to add something like the following to each pipeline to ensure it's always available (replace `example-pipeline` with the pipeline name):
```
  templates:
    daemon:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - daemon
                  - key: numaflow.numaproj.io/pipeline-name
                    operator: In
                    values:
                      - example-pipeline
              topologyKey: kubernetes.io/hostname
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: example-pipeline
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: daemon
      numaflow.numaproj.io/pipeline-name: example-pipeline
```

This isn't super important for me atm, but would be nice to support for a simpler production install.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
