### ISSUE TITLE
offset timeline store stuck when we have parallelism > 1 in sliding window

### ISSUE THREAD

**Issue by ashwinidulams** [numaproj/numaflow#480]
```{"level":"info","ts":1673845444.6196027,"logger":"numaflow.ReduceUDF-processor","caller":"fetch/edge_fetcher.go:116","msg":"[Processor: apigw-sliding-fixed-aggregation-0 status:active, timeline: [1673845440000:5877] -> [1673845380000:5279] -> [1673845320000:4672] -> [1673845260000:4020] -> [1673845200000:3453] -> [1673845140000:2885] -> [1673845080000:2331] -> [1673845020000:1766] -> [1673844960000:1160] -> [1673844900000:557]] \n[Processor: apigw-sliding-fixed-aggregation-1 status:active, timeline: [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1]] \n[Processor: apigw-sliding-fixed-aggregation-2 status:active, timeline: [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1]] \n[Processor: apigw-sliding-fixed-aggregation-3 status:active, timeline: [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1]] \n[Processor: apigw-sliding-fixed-aggregation-4 status:active, timeline: [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1]] \n[oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-fixed-aggregation-sliding-aggregation-0] get watermark for offset 5878: -1","vertex":"apigw-sliding-sliding-aggregation","bufferName":"oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-fixed-aggregation-sliding-aggregation-0"}
{"level":"info","ts":1673845445.0742857,"logger":"numaflow.ReduceUDF-processor","caller":"fetch/edge_fetcher.go:116","msg":"[Processor: apigw-sliding-fixed-aggregation-4 status:active, timeline: [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1]] \n[Processor: apigw-sliding-fixed-aggregation-0 status:active, timeline: [1673845440000:5877] -> [1673845380000:5279] -> [1673845320000:4672] -> [1673845260000:4020] -> [1673845200000:3453] -> [1673845140000:2885] -> [1673845080000:2331] -> [1673845020000:1766] -> [1673844960000:1160] -> [1673844900000:557]] \n[Processor: apigw-sliding-fixed-aggregation-1 status:active, timeline: [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1]] \n[Processor: apigw-sliding-fixed-aggregation-2 status:active, timeline: [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1]] \n[Processor: apigw-sliding-fixed-aggregation-3 status:active, timeline: [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1]] \n[oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-fixed-aggregation-sliding-aggregation-0] get watermark for offset 5901: -1","vertex":"apigw-sliding-sliding-aggregation","bufferName":"oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-fixed-aggregation-sliding-aggregation-0"}
{"level":"info","ts":1673845455.0189476,"logger":"numaflow.ReduceUDF-processor","caller":"fetch/edge_fetcher.go:116","msg":"[Processor: apigw-sliding-fixed-aggregation-0 status:active, timeline: [1673845440000:5877] -> [1673845380000:5279] -> [1673845320000:4672] -> [1673845260000:4020] -> [1673845200000:3453] -> [1673845140000:2885] -> [1673845080000:2331] -> [1673845020000:1766] -> [1673844960000:1160] -> [1673844900000:557]] \n[Processor: apigw-sliding-fixed-aggregation-1 status:active, timeline: [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1]] \n[Processor: apigw-sliding-fixed-aggregation-2 status:active, timeline: [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1]] \n[Processor: apigw-sliding-fixed-aggregation-3 status:active, timeline: [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1]] \n[Processor: apigw-sliding-fixed-aggregation-4 status:active, timeline: [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1]] \n[oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-fixed-aggregation-sliding-aggregation-0] get watermark for offset 6401: -1","vertex":"apigw-sliding-sliding-aggregation","bufferName":"oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-fixed-aggregation-sliding-aggregation-0"}
{"level":"info","ts":1673845506.5746186,"logger":"numaflow.ReduceUDF-processor","caller":"fetch/edge_fetcher.go:116","msg":"[Processor: apigw-sliding-fixed-aggregation-0 status:active, timeline: [1673845500000:6474] -> [1673845440000:5877] -> [1673845380000:5279] -> [1673845320000:4672] -> [1673845260000:4020] -> [1673845200000:3453] -> [1673845140000:2885] -> [1673845080000:2331] -> [1673845020000:1766] -> [1673844960000:1160]] \n[Processor: apigw-sliding-fixed-aggregation-1 status:active, timeline: [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1]] \n[Processor: apigw-sliding-fixed-aggregation-2 status:active, timeline: [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1]] \n[Processor: apigw-sliding-fixed-aggregation-3 status:active, timeline: [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1]] \n[Processor: apigw-sliding-fixed-aggregation-4 status:active, timeline: [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1]] \n[oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-fixed-aggregation-sliding-aggregation-0] get watermark for offset 6474: -1","vertex":"apigw-sliding-sliding-aggregation","bufferName":"oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-fixed-aggregation-sliding-aggregation-0"}
{"level":"info","ts":1673845506.6956205,"logger":"numaflow.ReduceUDF-processor","caller":"fetch/edge_fetcher.go:116","msg":"[Processor: apigw-sliding-fixed-aggregation-0 status:active, timeline: [1673845500000:6474] -> [1673845440000:5877] -> [1673845380000:5279] -> [1673845320000:4672] -> [1673845260000:4020] -> [1673845200000:3453] -> [1673845140000:2885] -> [1673845080000:2331] -> [1673845020000:1766] -> [1673844960000:1160]] \n[Processor: apigw-sliding-fixed-aggregation-1 status:active, timeline: [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1]] \n[Processor: apigw-sliding-fixed-aggregation-2 status:active, timeline: [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1]] \n[Processor: apigw-sliding-fixed-aggregation-3 status:active, timeline: [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1]] \n[Processor: apigw-sliding-fixed-aggregation-4 status:active, timeline: [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1] -> [-1:-1]] \n[oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-fixed-aggregation-sliding-aggregation-0] get watermark for offset 6480: -1","vertex":"apigw-sliding-sliding-aggregation","bufferName":"oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-fixed-aggregation-sliding-aggregation-0"}
```

```
~ # js kv ls
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                    Key-Value Buckets                                                                                     │
├─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────┬─────────────────────┬─────────┬────────┬─────────────┤
│ Bucket                                                                                                              │ Description │ Created             │ Size    │ Values │ Last Update │
├─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────┼─────────────────────┼─────────┼────────┼─────────────┤
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-sliding-aggregation-sink_OT                        │             │ 2023-01-16 04:54:59 │ 0 B     │ 0      │ never       │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-sink_SINK_OT                                       │             │ 2023-01-16 04:54:55 │ 0 B     │ 0      │ never       │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-sink_SINK_PROCESSORS                               │             │ 2023-01-16 04:54:56 │ 150 B   │ 1      │ 4.88s       │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-in-filter-keying_PROCESSORS                        │             │ 2023-01-16 04:54:57 │ 155 B   │ 1      │ 0.97s       │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-filter-keying-fixed-aggregation-0_PROCESSORS       │             │ 2023-01-16 04:54:51 │ 183 B   │ 1      │ 3.98s       │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-filter-keying-fixed-aggregation-1_PROCESSORS       │             │ 2023-01-16 04:54:39 │ 183 B   │ 1      │ 3.98s       │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-filter-keying-fixed-aggregation-2_PROCESSORS       │             │ 2023-01-16 04:54:53 │ 183 B   │ 1      │ 3.96s       │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-filter-keying-fixed-aggregation-4_PROCESSORS       │             │ 2023-01-16 04:54:49 │ 183 B   │ 1      │ 3.95s       │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-filter-keying-fixed-aggregation-3_PROCESSORS       │             │ 2023-01-16 04:54:55 │ 183 B   │ 1      │ 3.96s       │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-in-filter-keying_OT                                │             │ 2023-01-16 04:54:57 │ 765 B   │ 5      │ 4.64s       │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-sliding-aggregation-sink_PROCESSORS                │             │ 2023-01-16 04:54:59 │ 900 B   │ 5      │ 2.10s       │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-filter-keying-fixed-aggregation-4_OT               │             │ 2023-01-16 04:54:49 │ 905 B   │ 5      │ 3.72s       │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-filter-keying-fixed-aggregation-3_OT               │             │ 2023-01-16 04:54:54 │ 905 B   │ 5      │ 3.72s       │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-filter-keying-fixed-aggregation-2_OT               │             │ 2023-01-16 04:54:53 │ 905 B   │ 5      │ 3.71s       │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-filter-keying-fixed-aggregation-1_OT               │             │ 2023-01-16 04:54:39 │ 905 B   │ 5      │ 3.71s       │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-filter-keying-fixed-aggregation-0_OT               │             │ 2023-01-16 04:54:51 │ 905 B   │ 5      │ 3.71s       │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-fixed-aggregation-sliding-aggregation-3_OT         │             │ 2023-01-16 04:54:35 │ 955 B   │ 5      │ 12.88s      │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-fixed-aggregation-sliding-aggregation-4_OT         │             │ 2023-01-16 04:54:40 │ 955 B   │ 5      │ 12.90s      │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-fixed-aggregation-sliding-aggregation-0_OT         │             │ 2023-01-16 04:54:46 │ 955 B   │ 5      │ 12.89s      │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-fixed-aggregation-sliding-aggregation-2_OT         │             │ 2023-01-16 04:54:42 │ 955 B   │ 5      │ 12.93s      │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-fixed-aggregation-sliding-aggregation-1_OT         │             │ 2023-01-16 04:54:44 │ 955 B   │ 5      │ 12.87s      │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-fixed-aggregation-sliding-aggregation-3_PROCESSORS │             │ 2023-01-16 04:54:36 │ 965 B   │ 5      │ 0.43s       │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-fixed-aggregation-sliding-aggregation-4_PROCESSORS │             │ 2023-01-16 04:54:41 │ 965 B   │ 5      │ 0.42s       │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-fixed-aggregation-sliding-aggregation-0_PROCESSORS │             │ 2023-01-16 04:54:47 │ 965 B   │ 5      │ 0.45s       │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-fixed-aggregation-sliding-aggregation-2_PROCESSORS │             │ 2023-01-16 04:54:43 │ 965 B   │ 5      │ 0.44s       │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-fixed-aggregation-sliding-aggregation-1_PROCESSORS │             │ 2023-01-16 04:54:44 │ 965 B   │ 5      │ 0.44s       │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-in_SOURCE_PROCESSORS                               │             │ 2023-01-16 04:54:37 │ 1.7 KiB │ 12     │ 0.38s       │
│ apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-in_SOURCE_OT                                       │             │ 2023-01-16 04:54:36 │ 8.6 KiB │ 60     │ 0.57s       │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────┴─────────────────────┴─────────┴────────┴─────────────╯
```

```
~ # js kv watch apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-filter-keying-fixed-aggregation-1_OT
[2023-01-16 05:02:11] PUT apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-filter-keying-fixed-aggregation-1_OT > apigw-sliding-filter-keying-0: ;?.��
[2023-01-16 05:02:28] PUT apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-filter-keying-fixed-aggregation-1_OT > apigw-sliding-filter-keying-0: B?��
�2023-01-16 05:02:29] PUT apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-filter-keying-fixed-aggregation-1_OT > apigw-sliding-filter-keying-0: b@
[2023-01-16 05:02:31] PUT apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-filter-keying-fixed-aggregation-1_OT > apigw-sliding-filter-keying-0: AM�
^C
~ # ^C
~ # js kv watch apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-fixed-aggregation-sliding-aggregation-1_OT
[2023-01-16 05:02:05] PUT apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-fixed-aggregation-sliding-aggregation-1_OT > apigw-sliding-fixed-aggregation-1: *@��
[2023-01-16 05:03:04] PUT apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-fixed-aggregation-sliding-aggregation-1_OT > apigw-sliding-fixed-aggregation-1: ����
[2023-01-16 05:04:04] PUT apigw-sliding-oss-analytics-osamapigwnuma-usw2-qal-apigw-sliding-fixed-aggregation-sliding-aggregation-1_OT > apigw-sliding-fixed-aggregation-1: *~�
^C
```

**Comment by ashwinidulams** [comment]
```
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: apigw-sliding
spec:
  vertices:
    - name: in
      source:
        kafka:
          brokers:
            - eventbus-kafka.pl-data-lake-e2e.a.intuit.com:19701
            - eventbus-kafka.pl-data-lake-e2e.a.intuit.com:19704
            - eventbus-kafka.pl-data-lake-e2e.a.intuit.com:19703
            - eventbus-kafka.pl-data-lake-e2e.a.intuit.com:19904
            - eventbus-kafka.pl-data-lake-e2e.a.intuit.com:19903
            - eventbus-kafka.pl-data-lake-e2e.a.intuit.com:19901
            - eventbus-kafka.pl-data-lake-e2e.a.intuit.com:19802
            - eventbus-kafka.pl-data-lake-e2e.a.intuit.com:19902
            - eventbus-kafka.pl-data-lake-e2e.a.intuit.com:19803
            - eventbus-kafka.pl-data-lake-e2e.a.intuit.com:19801
            - eventbus-kafka.pl-data-lake-e2e.a.intuit.com:19702
            - eventbus-kafka.pl-data-lake-e2e.a.intuit.com:19804
          topic: ip-apigw-telegraf-druid
          consumerGroup: numaflow-apigw-24
          tls: # Optional.
            insecureSkipVerify: true
    - name: filter-keying
      volumes:
        - name: pipeline-conf
          configMap:
            name: pipeline-conf
      scale:
        min: 1
      udf:
        container:
          image: docker.intuit.com/oss-analytics/osam-apigw-numa/service/osam-apigw-numa:master-6c79ddc
          args: ["/opt/apigw-metrics/", "pipelineConfig", "filter-keying" ]
          volumeMounts:
            - mountPath: /opt/apigw-metrics/
              name: pipeline-conf
    - name: fixed-aggregation
      containerTemplate:
        env:
          - name: NUMAFLOW_DEBUG
            value: "true" # DO NOT forget the double quotes!!!
      volumes:
        - name: pipeline-conf
          configMap:
            name: pipeline-conf
      udf:
        container:
          image: docker.intuit.com/oss-analytics/osam-apigw-numa/service/osam-apigw-numa:master-6c79ddc
          args: ["/opt/apigw-metrics/", "pipelineConfig", "fixed-aggregation" ]
          env:
            - name: ID
              value: servicetoservice
          volumeMounts:
            - mountPath: /opt/apigw-metrics/
              name: pipeline-conf
        groupBy:
          window:
            fixed:
              length: 60s
          keyed: true
          storage:
            persistentVolumeClaim:
              volumeSize: 5Gi
              accessMode: ReadWriteOnce
    - name: sliding-aggregation
      containerTemplate:
        env:
          - name: NUMAFLOW_DEBUG
            value: "true" # DO NOT forget the double quotes!!!
        resources:
          limits:
            memory: 10240Mi
          requests:
            cpu: 1
            memory: 8192Mi
      volumes:
        - name: pipeline-conf
          configMap:
            name: pipeline-conf
      udf:
        container:
          # compute the sum
          image: docker.intuit.com/oss-analytics/osam-apigw-numa/service/osam-apigw-numa:master-6c79ddc
          args: ["/opt/apigw-metrics/", "pipelineConfig", "sliding-aggregation" ]
          volumeMounts:
            - mountPath: /opt/apigw-metrics/
              name: pipeline-conf
        groupBy:
          window:
            sliding:
              length: 600s
              slide: 60s
          keyed: true
          storage:
            persistentVolumeClaim:
              volumeSize: 5Gi
              accessMode: ReadWriteOnce
    - name: sink
      scale:
        min: 1
      sink:
       log: {}
  edges:
    - from: in
      to: filter-keying
    - from: filter-keying
      to: fixed-aggregation
      parallelism: 5
    - from: fixed-aggregation
      to: sliding-aggregation
      parallelism: 5
    - from: sliding-aggregation
      to: sink
```
