### ISSUE TITLE
Add support for specifying a runtimeClassName for vertices

### ISSUE THREAD

**Issue by gdsantoro** [numaproj/numaflow#518]
# Summary

Modify the pipeline CRD in order to allow to specify a custom runtimeClassName for vertices.  

# Use Cases

This addition would allow to expose a GPU to the training vertex/vertices in the pipeline when you use the [gpu-operator](https://github.com/NVIDIA/gpu-operator) helm chart (which allows pods to request a GPU by selecting the `nvidia` runtimeClass in their manifest).  

This addition would allow scenarios like the following, where we launch a stand-alone pod which needs access to a GPU:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: gpu
spec:
  restartPolicy: Never
  runtimeClassName: nvidia
  containers:
    - name: gpu
      image: "nvidia/cuda:11.8.0-base-ubuntu22.04"
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      resources:
        limits:
          nvidia.com/gpu: 1
```

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
