### ISSUE TITLE
Can not deploy JetStream/Redis on security harden cluster

### ISSUE THREAD

**Issue by sandangel** [numaproj/numaflow#526]
**Describe the bug**

The security harden k8s cluster requires some security best practices on deploy manifests:

```yaml
        securityContext:
          runAsNonRoot: true
          runAsUser: 9737
          runAsGroup: 9737
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
      serviceAccountName: '<sa-name>'
      automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '<sa-name>'
  namespace: numaflow-system
automountServiceAccountToken: false
``` 

- Need to specify resource usage
- Need to have liveliness, readiness probes
- Need to get image from internal mirror registries

Currently JetStream/Redis native does not meet these requirements so it is failed to install on the cluster. We can still patch numaflow-server and controller, but not JetStream/Redis native. Right now the solution is to switch to external redis stream

**To Reproduce**

1. ....
2. ....
3. ....

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- Kubernetes: [e.g. v1.18.6]
- Numaflow: 0.7.0

**Additional context**

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.
