### ISSUE TITLE
Vertex keeps scaling out even there is 0 pending (ackpending > 0)

### ISSUE THREAD

**Issue by sandangel** [numaproj/numaflow#630]
**Describe the bug**

**To Reproduce**

```yaml
# Pipeline spec
limits:
    readBatchSize: 1
    bufferMaxLength: 500
    bufferUsageLimit: 50

    # Vertex spec:
      scale:
        min: 0
        max: 200
        lookbackSeconds: 420
        cooldownSeconds: 60
        zeroReplicaSleepSeconds: 60
        targetBufferAvailability: 100
        replicasPerScale: 20
```

You produce new message that take vertex 7 mins to process, then you'll see even there is only 4 items in the ackpending, and 0 pending item, the vertex still scale out to 73

More information in Slack thread: https://numaproj.slack.com/archives/C03GQ3AMHE1/p1679303465992269

**Expected behavior**

It should stay at 4 pods instead of scale out to 73

**Screenshots**

<img src="https://numaproj.slack.com/files/U04N16MMEA1/F04UST0JGGL/image.png" alt="Pipeline" style="height: 100px; width:100px;" />

**Environment (please complete the following information):**

- Kubernetes: [e.g. v1.18.6]
- Numaflow: [e.g. v0.5.1]

**Additional context**

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.
