### ISSUE TITLE
Pipelines unable to perform actions on the ISB though the service is up 

### ISSUE THREAD

**Issue by louisnow** [numaproj/numaflow#752]
**Describe the bug**

In the init step of the vertex we see the following logs 
```
{"level":"info","ts":1685012075.0670965,"logger":"numaflow.isbsvc-buffer-create","caller":"nats/default_jetstream_client.go:74","msg":"Nats: connected to nats server"}
{"level":"info","ts":1685012075.067276,"logger":"numaflow.isbsvc-buffer-create","caller":"nats/in_cluster_jetstream_client.go:86","msg":"Starting Nats JetStream auto reconnection daemon..."}
{"level":"error","ts":1685012075.0875037,"logger":"numaflow.isbsvc-buffer-create","caller":"commands/isbsvc_buffer_create.go:90","msg":"Failed to create buffers.","error":"failed to create offset timeline bucket \"atlan-nf-pipe-sq-enricher-rtn-default-atlan-nf-pipe-sq-enricher-rtn-failed-sync-sink-2_SINK_OT\", nats: no suitable peers for placement, peer offline","stacktrace":"github.com/numaproj/numaflow/cmd/commands.NewISBSvcBufferCreateCommand.func1\n\t/home/runner/work/numaflow/numaflow/cmd/commands/isbsvc_buffer_create.go:90\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902\ngithub.com/numaproj/numaflow/cmd/commands.Execute\n\t/home/runner/work/numaflow/numaflow/cmd/commands/root.go:32\nmain.main\n\t/home/runner/work/numaflow/numaflow/cmd/main.go:24\nruntime.main\n\t/opt/hostedtoolcache/go/1.19.8/x64/src/runtime/proc.go:250"}
Error: failed to create offset timeline bucket "atlan-nf-pipe-sq-enricher-rtn-default-atlan-nf-pipe-sq-enricher-rtn-failed-sync-sink-2_SINK_OT", nats: no suitable peers for placement, peer offline
Usage:
  numaflow isbsvc-buffer-create [flags]

Flags:
      --buffers stringToString   Buffers to create (default [])
  -h, --help                     help for isbsvc-buffer-create
      --isbsvc-type string       ISB Service type, e.g. jetstream (default "jetstream")

panic: failed to create offset timeline bucket "atlan-nf-pipe-sq-enricher-rtn-default-atlan-nf-pipe-sq-enricher-rtn-failed-sync-sink-2_SINK_OT", nats: no suitable peers for placement, peer offline

goroutine 1 [running]:
github.com/numaproj/numaflow/cmd/commands.Execute()
	/home/runner/work/numaflow/numaflow/cmd/commands/root.go:33 +0x45
main.main()
	/home/runner/work/numaflow/numaflow/cmd/main.go:24 +0x17
```

In the create buffer Job that is started automatically, we see the following error.
```
{"level":"info","ts":1685012836.7597451,"logger":"numaflow.isbsvc-buffer-create","caller":"nats/default_jetstream_client.go:74","msg":"Nats: connected to nats server"}
{"level":"info","ts":1685012836.7599213,"logger":"numaflow.isbsvc-buffer-create","caller":"nats/in_cluster_jetstream_client.go:86","msg":"Starting Nats JetStream auto reconnection daemon..."}
{"level":"info","ts":1685012836.7623348,"logger":"numaflow.isbsvc-buffer-create","caller":"nats/default_jetstream_client.go:62","msg":"Nats: disconnected"}
{"level":"error","ts":1685012836.7623699,"logger":"numaflow.isbsvc-buffer-create","caller":"commands/isbsvc_buffer_create.go:90","msg":"Failed to create buffers.","error":"failed to create stream \"atlan-nf-pipe-webhooks-default-atlan-nf-pipe-webhooks-filter-executer\" and buffers, nats: no suitable peers for placement, peer offline","stacktrace":"github.com/numaproj/numaflow/cmd/commands.NewISBSvcBufferCreateCommand.func1\n\t/home/runner/work/numaflow/numaflow/cmd/commands/isbsvc_buffer_create.go:90\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902\ngithub.com/numaproj/numaflow/cmd/commands.Execute\n\t/home/runner/work/numaflow/numaflow/cmd/commands/root.go:32\nmain.main\n\t/home/runner/work/numaflow/numaflow/cmd/main.go:24\nruntime.main\n\t/opt/hostedtoolcache/go/1.19.8/x64/src/runtime/proc.go:250"}
Error: failed to create stream "atlan-nf-pipe-webhooks-default-atlan-nf-pipe-webhooks-filter-executer" and buffers, nats: no suitable peers for placement, peer offline
Usage:
  numaflow isbsvc-buffer-create [flags]

Flags:
      --buffers stringToString   Buffers to create (default [])
  -h, --help                     help for isbsvc-buffer-create
      --isbsvc-type string       ISB Service type, e.g. jetstream (default "jetstream")

panic: failed to create stream "atlan-nf-pipe-webhooks-default-atlan-nf-pipe-webhooks-filter-executer" and buffers, nats: no suitable peers for placement, peer offline

goroutine 1 [running]:
github.com/numaproj/numaflow/cmd/commands.Execute()
	/home/runner/work/numaflow/numaflow/cmd/commands/root.go:33 +0x45
main.main()
	/home/runner/work/numaflow/numaflow/cmd/main.go:24 +0x17
```

In every Vertex pod's init container, we see the following logs. 
```
{"level":"info","ts":1685012496.8251655,"logger":"numaflow.isbsvc-buffer-validate","caller":"commands/isbsvc_buffer_validate.go:77","msg":"Buffers might have not been created yet, will retry if the limit is not reached","error":"failed to query OT bucket \"atlan-nf-pipe-webhooks-default-atlan-nf-pipe-webhooks-kafka-source_SOURCE_OT\", nats: bucket not found"}
{"level":"info","ts":1685012504.275315,"logger":"numaflow.isbsvc-buffer-validate","caller":"nats/in_cluster_jetstream_client.go:90","msg":"Nats JetStream connection lost"}
{"level":"info","ts":1685012504.2835822,"logger":"numaflow.isbsvc-buffer-validate","caller":"nats/default_jetstream_client.go:74","msg":"Nats: connected to nats server"}
{"level":"info","ts":1685012504.2836359,"logger":"numaflow.isbsvc-buffer-validate","caller":"nats/in_cluster_jetstream_client.go:101","msg":"Succeeded to reconnect to Nat JetStream server"}
{"level":"info","ts":1685012518.2079148,"logger":"numaflow.isbsvc-buffer-validate","caller":"nats/default_jetstream_client.go:74","msg":"Nats: connected to nats server"}
{"level":"info","ts":1685012518.208038,"logger":"numaflow.isbsvc-buffer-validate","caller":"nats/in_cluster_jetstream_client.go:86","msg":"Starting Nats JetStream auto reconnection daemon..."}
{"level":"info","ts":1685012518.2095568,"logger":"numaflow.isbsvc-buffer-validate","caller":"nats/default_jetstream_client.go:62","msg":"Nats: disconnected"}
{"level":"info","ts":1685012518.209578,"logger":"numaflow.isbsvc-buffer-validate","caller":"commands/isbsvc_buffer_validate.go:77","msg":"Buffers might have not been created yet, will retry if the limit is not reached","error":"failed to query OT bucket \"atlan-nf-pipe-webhooks-default-atlan-nf-pipe-webhooks-kafka-source_SOURCE_OT\", nats: bucket not found"}
{"level":"info","ts":1685012529.4814084,"logger":"numaflow.isbsvc-buffer-validate","caller":"nats/in_cluster_jetstream_client.go:90","msg":"Nats JetStream connection lost"}
{"level":"info","ts":1685012529.4863942,"logger":"numaflow.isbsvc-buffer-validate","caller":"nats/default_jetstream_client.go:74","msg":"Nats: connected to nats server"}
{"level":"info","ts":1685012529.4864502,"logger":"numaflow.isbsvc-buffer-validate","caller":"nats/in_cluster_jetstream_client.go:101","msg":"Succeeded to reconnect to Nat JetStream server"}
{"level":"info","ts":1685012559.053798,"logger":"numaflow.isbsvc-buffer-validate","caller":"nats/default_jetstream_client.go:74","msg":"Nats: connected to nats server"}
{"level":"info","ts":1685012559.0540361,"logger":"numaflow.isbsvc-buffer-validate","caller":"nats/in_cluster_jetstream_client.go:86","msg":"Starting Nats JetStream auto reconnection daemon..."}
{"level":"info","ts":1685012559.0594714,"logger":"numaflow.isbsvc-buffer-validate","caller":"commands/isbsvc_buffer_validate.go:77","msg":"Buffers might have not been created yet, will retry if the limit is not reached","error":"failed to query OT bucket \"atlan-nf-pipe-webhooks-default-atlan-nf-pipe-webhooks-kafka-source_SOURCE_OT\", nats: bucket not found"}
{"level":"info","ts":1685012559.0595188,"logger":"numaflow.isbsvc-buffer-validate","caller":"nats/default_jetstream_client.go:62","msg":"Nats: disconnected"}
{"level":"info","ts":1685012570.567665,"logger":"numaflow.isbsvc-buffer-validate","caller":"nats/in_cluster_jetstream_client.go:90","msg":"Nats JetStream connection lost"}
{"level":"info","ts":1685012570.5744648,"logger":"numaflow.isbsvc-buffer-validate","caller":"nats/default_jetstream_client.go:74","msg":"Nats: connected to nats server"}
{"level":"info","ts":1685012570.5745041,"logger":"numaflow.isbsvc-buffer-validate","caller":"nats/in_cluster_jetstream_client.go:101","msg":"Succeeded to reconnect to Nat JetStream server"}
```

**To Reproduce**

1. This is happening to a handful of our pipelines.
2. Restarting the ISB service fixes it. There are no error logs from the ISB service pods that indicate something is going wrong when the request fails from the init container.

**Expected behavior**
- Pipeline to be able to initialise itself with the ISB correctly without needing an ISB restart

**Screenshots**

**Environment (please complete the following information):**

- Kubernetes: 1.24
- Numaflow: 0.8.0
- nats:2.9.15
- nats-server-config-reloader:0.7.0
- prometheus-nats-exporter:0.9.1

**Additional context**

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by vigith** [comment]
> nats: no suitable peers for placement, peer offline

looks like the ISB is down. could you please share the ISB pod logs? Does deleting and recreating the ISB solve the issue?

**Comment by louisnow** [comment]
[ISB-logs.csv](https://github.com/numaproj/numaflow/files/11565445/ISB-logs.csv)
I've attached the ISB logs, it's in reverse order.
On May 25 today, I restarted the service and it fixed itself. 
Prior to that, there are only logs on 12th/16th of May which is when the issue likely began.

**Comment by vigith** [comment]
I do see some network errors in logs 

```
"May 25, 2023 @ 16:43:03.484","[13] 2023/05/25 11:13:03.484077 [ERR] Error trying to connect to route (attempt 10): lookup for host ""isbsvc-default-js-1.isbsvc-default-js-svc.default.svc.cluster.local"": lookup isbsvc-def
ault-js-1.isbsvc-default-js-svc.default.svc.cluster.local on 172.20.112.147:53: no such host"
"May 25, 2023 @ 16:43:02.666","[13] 2023/05/25 11:13:02.665983 [ERR] Error trying to connect to route (attempt 8): lookup for host ""isbsvc-default-js-0.isbsvc-default-js-svc.default.svc.cluster.local"": lookup isbsvc-defa
ult-js-0.isbsvc-default-js-svc.default.svc.cluster.local on 172.20.112.147:53: no such host"
```

Do you have PDB?

**Comment by whynowy** [comment]
@louisnow - can you share your isbsvc spec?

**Comment by louisnow** [comment]
This is the ISB spec
```
apiVersion: numaflow.numaproj.io/v1alpha1
kind: InterStepBufferService
metadata:
  # "InterStepBufferService" is a namespaced object, it can be used by all the Pipelines in the same namespace.
  name: default
spec:
  jetstream:
    version: 2.9.15
    persistence:
      volumeSize: 8Gi
    imagePullSecrets:
    - name: github-docker-registry
```

From the controller configmap, I've used the default values as is
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: numaflow-controller-config
  namespace: numaflow
data:
  controller-config.yaml: |
      jetstream:
        # Default JetStream settings, could be overridden by InterStepBufferService specs
        settings: |
          # https://docs.nats.io/running-a-nats-service/configuration#jetstream
          # Only configure "max_memory_store" or "max_file_store", do not set "store_dir" as it has been hardcoded.
          # e.g. 1G. -1 means no limit, up to 75% of available memory. This only take effect for streams created using memory storage.
          max_memory_store: -1
          # e.g. 20G. -1 means no limit, Up to 1TB if available
          max_file_store: 1TB
        bufferConfig: |
          # The default properties of the buffers (streams) to be created in this JetStream service
          stream:
            # 0: Limits, 1: Interest, 2: WorkQueue
            retention: 0
            maxMsgs: 100000
            maxAge: 72h
            maxBytes: -1
            # 0: File, 1: Memory
            storage: 0
            replicas: 3
            duplicates: 60s
          # The default consumer properties for the created streams
          consumer:
            ackWait: 60s
            maxAckPending: 25000
          otBucket:
            maxValueSize: 0
            history: 5
            ttl: 3h
            maxBytes: 0
            # 0: File, 1: Memory
            storage: 0
            replicas: 3
          procBucket:
            maxValueSize: 0
            history: 1
            ttl: 72h
            maxBytes: 0
            # 0: File, 1: Memory
            storage: 0
            replicas: 3
```

**Comment by louisnow** [comment]
If I port forward the service, `localhost:8222/healthz` returns 503. `{"status":"unavailable","error":"JetStream not enabled (10076)"}`

I checked the ISB spec that finally gets deployed by numaflow, the liveness probe is set incorrectly to `/` instead of `/healthz` and so it never restarts automatically
```
      livenessProbe:
        httpGet:
          path: /
          port: 8222
          scheme: HTTP
        initialDelaySeconds: 10
        timeoutSeconds: 5
        periodSeconds: 30
        successThreshold: 1
        failureThreshold: 3
      startupProbe:
        httpGet:
          path: /healthz
          port: 8222
          scheme: HTTP
        initialDelaySeconds: 10
        timeoutSeconds: 5
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 30
```
