### ISSUE TITLE
Revisit numDelivered

### ISSUE THREAD

**Issue by jy4096** [numaproj/numaflow#799]
# Test run (local, using kind)
## Test Pipeline
```yaml
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: test-retry
spec:
  vertices:
  - name: in
    source:
      http: {}
  - name: forward-message
    scale:
      min: 1
    udf:
      container:
        image: quay.io/numaio/numaflow-go/map-forward-message-test:latest
  - name: log-output
    sink:
      log: {}
  edges:
  - from: in
    to: forward-message
  - from: forward-message
    to: log-output
```

## Test UDF in golang
The handler will exit and restart the UDF container
Built an image `quay.io/numaio/numaflow-go/map-forward-message-test:latest` with the following code
```golang
package main

import (
	"context"
	"log"
	"os"

	functionsdk "github.com/numaproj/numaflow-go/pkg/function"
	"github.com/numaproj/numaflow-go/pkg/function/server"
)

func mapHandle(_ context.Context, keys []string, d functionsdk.Datum) functionsdk.Messages {
	val := d.Value()
	log.Print(d.Metadata().NumDelivered(), string(val))
	os.Exit(1)
	return nil
}

func main() {
	server.New().RegisterMapper(functionsdk.MapFunc(mapHandle)).Start(context.Background())
}
```

## Steps
Use port-forward and send `curl -kq -X POST -d "101" https://localhost:8444/vertices/in`
Expect to see `d.Metadata().NumDelivered()` gets increased after UDF restarts.

Actual results: (I forgot to add a space between numDelivered and value, it should be `1 101`)
![image](https://github.com/numaproj/numaflow/assets/19543684/7cb4ba0a-f8cb-43ed-b1d4-ad884afc03d5)

## Potential root cause
Need to fix and clean up the retry logic https://github.com/numaproj/numaflow/blob/main/pkg/forward/forward.go#L707-L718 because we've added the "retry 5 times" in https://github.com/numaproj/numaflow/pull/744/files#diff-0c876de13c4addba8242fe3b40e5fd1eb0f3daab316cf0cbb51eb6c3cd1b8ba0R108-R114 for retryable errors.

May need to do the same for MapTransformer
