### ISSUE TITLE
multi-partition issues when running endurance test with 21k tps

### ISSUE THREAD

**Issue by yhl25** [numaproj/numaflow#823]
- [x] Pods View is slow when there are 50 pods.
- [x] Processing rate is zero when there are 50 pods.
- [x] Autoscaling is not working

<img width="1552" alt="Screenshot 2023-07-01 at 10 22 58 PM" src="https://github.com/numaproj/numaflow/assets/109710325/e945e7a4-4a23-45f5-9405-c577291df9ee">

pipeline spec
```yaml
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  vertices:
    - name: in
      scale:
        min: 1
      source:
        generator:
          keyCount: 100
          msgSize: 1000
          rpu: 30
          duration: 1s
    - name: first-cat
      partitions: 3
      scale:
        min: 1
      udf:
        builtin:
          name: cat
    - name: second-cat
      partitions: 2
      scale:
        min: 1
      udf:
        builtin:
          name: cat
    - name: third-cat
      partitions: 3
      scale:
        min: 1
      udf:
        builtin:
          name: cat
    - name: out
      partitions: 3
      scale:
        min: 1
      sink:
        log: {}
  edges:
    - from: in
      to: first-cat
    - from: first-cat
      to: second-cat
    - from: second-cat
      to: third-cat
    - from: third-cat
      to: out
```
