### ISSUE TITLE
UDF health check will pass if a map UDF is passed to a reduce vertex

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#908]
Since we have the same health-check for Map and Reduce, the health check will pass immaterial of whether it is Map UDF or Reduce UDF.

```yaml
  udf:
    container:
      # count element
      image: quay.io/numaio/numaflow-rs-counter:v2
    groupBy:
      ...
      keyed: true
      storage:
        ...
```
